// コマンドごとの「意味のある習得レベル」定義。
// 設計ルール:
//  - 合格基準は必ず測定・判定可能（成功回数 / 反応時間 / 維持秒数 / 距離 / 回数）。
//  - 条件も曖昧さをなくす（距離はm、誘惑は具体物、場所は◯か所）。
//  - 飼い主1人で完結する状況のみ（2人必須の設定は禁止）。
//  - 各レベルは「意味のある飛び」を持つ（成立だけの薄い段は作らない）。
//  - 他コマンドへの依存は requires（"commandId:Ln"）で表す。
//  - testType はアプリのテストUIを決める:
//      trial    試行型   … 設定した状況を複数回作り「成功/失敗」を数える
//      duration 維持型   … 指定秒数/分を保てるか（タイマー）
//      tally    実地集計型 … 散歩等で機会が来るたび記録し、しきい値で合格

export type TestType = "trial" | "duration" | "tally";

export const testTypeLabels: Record<TestType, string> = {
  trial: "回数で合格",
  duration: "時間キープで合格",
  tally: "おでかけ中に記録",
};

// アプリの自動採点用の構造化フィールド。criterion（人間用の文章）から数値を抜き出したもの。
// Web表示は criterion をそのまま使い、アプリは measure で合否を機械判定する。
export interface Measure {
  trials?: number; // 試行/機会の回数（10回中… の 10）
  successes?: number; // 合格に必要な成功回数（10回中8回 の 8）
  consecutive?: boolean; // 連続成功が必要か（「N回連続」）
  maxLatencySec?: number; // 号令→完了の制限時間（秒）
  noRepeatCue?: boolean; // 号令の言い直し不可
  holdSeconds?: number; // 維持する秒数（duration）
  reps?: number; // 維持の成功セット数 / 試技数
  places?: number; // 異なる場所の数（般化）
  streakDays?: number; // 連続日数（粗相ゼロ等）
  maxFaults?: number; // 許容失敗回数の上限（引っ張り回数など）
  overSteps?: number; // 評価対象の歩数（ゆるリード/ヒール）
}

export interface CommandLevel {
  level: number;
  condition: string; // この状況でできる（一言の要約）
  steps?: string[]; // 「やること」の再現可能な手順（番号つきで表示）。あれば condition より優先表示
  criterion: string; // 測定・判定可能な合格基準
  reason: string; // 得られる価値（なぜこの条件をやるか）
  testType: TestType;
  measure?: Measure; // アプリ自動採点用（criterion を数値化）
  requires?: string[]; // 他コマンドのレベル依存 例:["leave-it:L1"]
}

// commandId（commands.ts の id）→ レベル列
export const commandLevels: Record<string, CommandLevel[]> = {
  // ───────── 土台ツール ─────────
  marker: [
    {
      level: 1,
      condition: "「Yes」＝おやつ、を覚えさせる（充電）。",
      steps: [
        "静かな部屋で、犬が落ち着いているときに「Yes」と1回言う。",
        "言ったらすぐ（1秒以内）におやつをあげる。犬は何もしなくてよい。",
        "言う間隔をバラバラにして、10〜20回くり返す。",
      ],
      criterion: "「Yes」と言った瞬間に、パッと手元や顔を見る、5回続けて。",
      reason: "「Yes＝ご褒美」の結びつきを作る。すべての練習の土台。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
    },
    {
      level: 2,
      condition: "外でも「Yes」を効かせる。",
      steps: [
        "自宅の外の1か所で「Yes」と言う。",
        "すぐおやつをあげる。",
        "「Yes」で犬がパッとこちらを見れば、外でも効いている。",
      ],
      criterion: "「Yes」で即座に視線を向ける、5回続けて。",
      reason: "場所が変わっても「Yes」が効く。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1"],
    },
  ],

  release: [
    {
      level: 1,
      condition: "「ブレイク」＝動いてよい、を覚えさせる。",
      steps: [
        "犬を座らせる（または伏せ）。1〜2秒、その姿勢を保たせる。",
        "明るい声で「ブレイク」と言い、同時に床へおやつを投げて動くよう促す。",
        "ブレイクで動いたら、おやつを食べさせる。これをくり返す。",
      ],
      criterion: "「ブレイク」で姿勢を解いて動く、10回中9回。",
      reason: "「いつ動いてよいか」を伝える合図。まて系すべての前提。",
      testType: "trial",
      measure: { trials: 10, successes: 9 },
      requires: ["sit:L4", "marker:L1"],
    },
    {
      level: 2,
      condition: "どこでも・どの姿勢でも「ブレイク」で解放する。",
      steps: [
        "屋外や、伏せ・立ちなど別の姿勢でも「ブレイク」と言う。",
        "解放されて動いたらOK。",
      ],
      criterion: "解除の言葉で解放できる、10回中8回。",
      reason: "どこでも・どの姿勢でも解除が効く。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["release:L1"],
    },
  ],

  // ───────── 注目・誘導 ─────────
  "name-response": [
    {
      level: 1,
      condition: "名前を呼んで、振り向かせる。",
      steps: [
        "静かな部屋で、犬の名前を1回呼ぶ。",
        "犬がこちらへ顔を向けた瞬間に「Yes」→おやつ。",
        "最初は振り向かなくても、名前のあとにおやつを出して『名前＝良いこと』にしてよい。",
      ],
      criterion: "2秒以内にこちらへ顔を向ける、10回中8回で合格。",
      reason: "名前＝「こっちを見て」を覚える、すべての起点。",
      testType: "trial",
      measure: { maxLatencySec: 2, trials: 10, successes: 8 },
      requires: ["marker:L1"],
    },
    {
      level: 2,
      condition: "気を引いた状態で名前を呼ぶ。",
      steps: [
        "床におもちゃを置いて、犬の気を引いておく。",
        "名前を1回呼ぶ。",
        "おもちゃから離れて振り向いたら「Yes」→おやつ。",
      ],
      criterion: "おもちゃから離れて振り向く、10回中8回。",
      reason: "何かに夢中でも振り向く。",
      testType: "trial",
      measure: { maxLatencySec: 2, trials: 10, successes: 8 },
      requires: ["name-response:L1"],
    },
    {
      level: 3,
      condition: "見えない所から名前を呼ぶ。",
      steps: [
        "別の部屋（姿が見えない所）へ行く。",
        "名前を1回呼ぶ。",
        "来る／顔を向けたら「Yes」→おやつ。",
      ],
      criterion: "3秒以内に来る／顔を向ける、10回中8回。",
      reason: "見えなくても反応する。",
      testType: "trial",
      measure: { maxLatencySec: 3, trials: 10, successes: 8 },
      requires: ["name-response:L1"],
    },
    {
      level: 4,
      condition: "屋外で名前を呼ぶ（場所を変えて）。",
      steps: [
        "自宅の外、静かな場所へ行く。",
        "名前を1回呼ぶ。",
        "振り向いたら「Yes」→おやつ。別の場所でも試す。",
      ],
      criterion: "各場所で2秒以内に振り向く、各10回中8回。",
      reason: "外でも注意が向く（散歩の安全）。",
      testType: "trial",
      measure: { maxLatencySec: 2, trials: 10, successes: 8 },
      requires: ["name-response:L1"],
    },
    {
      level: 5,
      condition: "人や犬がいる公園で名前を呼ぶ。",
      steps: [
        "人や犬がいる公園に、リードをつけて行く。",
        "刺激がある中で名前を1回呼ぶ。",
        "振り向いたら「Yes」→おやつ。できなければ刺激から少し離れてやり直す。",
      ],
      criterion: "機会10回中、2秒以内に振り向くのが7回以上。",
      reason: "刺激の中でも“まず飼い主を見る”＝安全と絆の核。",
      testType: "tally",
      measure: { maxLatencySec: 2, trials: 10, successes: 7 },
      requires: ["name-response:L4"],
    },
  ],

  "watch-me": [
    {
      level: 1,
      condition: "「見て」で目を合わせる。",
      steps: [
        "静かな部屋で、最初はおやつを自分の目の高さに持って犬の注意を引く。",
        "「見て」と1回言う。",
        "目が合った瞬間に「Yes」→おやつ。慣れたらおやつで誘導せず、言葉だけにする。",
      ],
      criterion: "2秒以内に目が合う、10回中8回で合格。",
      reason: "集中の入口を作る。",
      testType: "trial",
      measure: { maxLatencySec: 2, trials: 10, successes: 8 },
      requires: ["marker:L1", "name-response:L1"],
    },
    {
      level: 2,
      condition: "目を合わせ続けさせる。",
      steps: [
        "「見て」で目を合わせる。",
        "すぐ渡さず、心の中で3秒数える。",
        "3秒間そらさず見ていられたら「Yes」→おやつ。そらしたら1秒に短くしてやり直す。",
      ],
      criterion: "視線を3秒間そらさない、5回続けて。",
      reason: "見続けられるようにする。",
      testType: "duration",
      measure: { holdSeconds: 3, reps: 5, consecutive: true },
      requires: ["watch-me:L1"],
    },
    {
      level: 3,
      condition: "おやつの誘惑がある中で目を見させる。",
      steps: [
        "おやつを持った手を、体の横にまっすぐ出す。",
        "「見て」と言う。",
        "手のおやつでなく、あなたの目を見たら「Yes」→おやつ。",
      ],
      criterion: "手でなく、目を見る、10回中8回。",
      reason: "「おやつより飼い主」を選ぶ＝信頼の芽。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["watch-me:L1"],
    },
    {
      level: 4,
      condition: "屋外で「見て」（場所を変えて）。",
      steps: [
        "自宅の外、静かな場所へ行く。",
        "「見て」と言う。",
        "目が合ったら「Yes」→おやつ。別の場所でも試す。",
      ],
      criterion: "各場所で2秒以内に目が合う、各10回中8回。",
      reason: "外でも集中できる。",
      testType: "trial",
      measure: { maxLatencySec: 2, trials: 10, successes: 8 },
      requires: ["watch-me:L2"],
    },
    {
      level: 5,
      condition: "人や犬が遠くにいる公園で「見て」。",
      steps: [
        "人や犬が遠くにいる公園に、リードをつけて行く。",
        "「見て」と言う。",
        "5秒間そらさず見ていられたら「Yes」→おやつ。できなければ刺激から少し離れてやり直す。",
      ],
      criterion: "視線を5秒間保つ、10回中7回。",
      reason: "すれ違いや興奮を予防する。絆の核。",
      testType: "duration",
      measure: { holdSeconds: 5, trials: 10, successes: 7 },
      requires: ["watch-me:L4"],
    },
  ],

  touch: [
    {
      level: 1,
      condition: "手のひらに鼻でタッチさせる。",
      steps: [
        "手のひらを開いて、犬の鼻先10cmくらいに出す。",
        "犬が興味を持って鼻でツンと触れた瞬間に「Yes」→おやつ。",
        "触れないときは、手に少しおやつのにおいをつけて誘ってよい。",
      ],
      criterion: "鼻が手のひらに触れる、5回続けて。",
      reason: "誘導に使える万能ツールを手に入れる。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1"],
    },
    {
      level: 2,
      condition: "「タッチ」と言ってタッチさせる。",
      steps: [
        "「タッチ」と1回言ってから手を出す。",
        "鼻が手に触れたら「Yes」→おやつ。",
      ],
      criterion: "言葉1回で手に触れる、10回中8回。",
      reason: "言葉でタッチできるようにする。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["touch:L1"],
    },
    {
      level: 3,
      condition: "いろいろな位置でタッチさせる。",
      steps: [
        "手を上・下・左・右と、いろいろな位置に出して「タッチ」。",
        "どの位置でも触れたら「Yes」→おやつ。",
      ],
      criterion: "どの位置でも手に触れる、各10回中8回。",
      reason: "手で体勢や移動を自在に誘導できる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["touch:L2"],
    },
    {
      level: 4,
      condition: "離れた手にタッチさせる。",
      steps: [
        "手を2〜3歩離れた所に出して「タッチ」。",
        "犬が移動してきて手に触れたら「Yes」→おやつ。",
      ],
      criterion: "移動して手に触れる、10回中8回。",
      reason: "呼び寄せや移動の誘導に使える。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["touch:L3"],
    },
    {
      level: 5,
      condition: "誘惑がある中でタッチさせる。",
      steps: [
        "床におやつを置いた状態で、手を出して「タッチ」。",
        "床のおやつを無視して手に触れたら「Yes」→手持ちの別のおやつ。",
      ],
      criterion: "おやつを無視して手に触れる、10回中8回。",
      reason: "不安・興奮したときに気持ちを切り替えるリセットになる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["touch:L3"],
    },
    {
      level: 6,
      condition: "屋外でタッチさせる（場所を変えて）。",
      steps: [
        "自宅の外、静かな場所へ行き、手を出して「タッチ」。",
        "触れたら「Yes」→おやつ。別の場所でも試す。",
      ],
      criterion: "各場所で手に触れる、各10回中8回。",
      reason: "怖い物の横を、手で誘導して通り抜けられる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["touch:L5"],
    },
  ],

  // ───────── 生活管理コマンド ─────────
  potty: [
    {
      level: 1,
      condition: "「ワンツー」＝排泄、を覚えさせる。",
      steps: [
        "起床直後・食後・遊んだ後など、排泄しそうなタイミングでトイレへ連れて行く。",
        "犬が排泄し“始めた”瞬間に、静かに「ワンツー」と言う（じゃまをしない声量で）。",
        "終わった直後に「Yes」→その場でおやつ。",
      ],
      criterion: "排泄中に号令を被せられた回数が、1日3回以上を3日間（記録）。",
      reason: "「ワンツー＝排泄」の結びつきを作る。",
      testType: "tally",
      measure: { streakDays: 3 },
      requires: ["marker:L1"],
    },
    {
      level: 2,
      condition: "号令で排泄をうながす。",
      steps: [
        "トイレ／指定の場所へ連れて行く。",
        "先に「ワンツー」と言ってうながす。",
        "2分以内に排泄したら「Yes」→おやつ。",
      ],
      criterion: "号令後2分以内に排泄する、10回中7回。",
      reason: "外出や就寝の前に、排泄を済ませられる。",
      testType: "trial",
      measure: { trials: 10, successes: 7 },
      requires: ["potty:L1"],
    },
    {
      level: 3,
      condition: "屋外でも号令で排泄させる。",
      steps: [
        "散歩中の、いつもの排泄ポイントへ行く。",
        "「ワンツー」と言ってうながす。",
        "3分以内に排泄したら「Yes」→おやつ。",
      ],
      criterion: "号令後3分以内に排泄する、10回中7回。",
      reason: "外でも号令で排泄できる（旅行・雨の前に便利）。",
      testType: "trial",
      measure: { trials: 10, successes: 7 },
      requires: ["potty:L2"],
    },
    {
      level: 4,
      condition: "室内の粗相をゼロにする（管理込み）。",
      steps: [
        "こまめにトイレへ連れて行き、成功をほめる生活を続ける。",
        "失敗は無言で片付け、叱らない。",
        "室内での粗相が連続14日間ゼロになれば完成。",
      ],
      criterion: "室内での粗相が連続14日間ゼロ。",
      reason: "トイレの完成（日常で困らない）。",
      testType: "tally",
      measure: { streakDays: 14 },
      requires: ["potty:L2"],
    },
  ],

  crate: [
    {
      level: 1,
      condition: "おやつで誘導してクレートに入らせる。",
      steps: [
        "クレートのドアを開けて固定しておく。",
        "おやつをクレートの奥へ投げる。",
        "全身が入ったら「Yes」→中でもう数粒おやつ（中＝良い場所にする）。",
      ],
      criterion: "全身がクレートに入る、5回続けて。",
      reason: "「入る」を覚える＋クレートを好きにする。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1"],
    },
    {
      level: 2,
      condition: "「ハウス」の言葉で入らせる。",
      steps: [
        "おやつを投げず、「ハウス」と1回言う。",
        "3秒以内に全身が入ったら「Yes」→中でおやつ。",
      ],
      criterion: "3秒以内に全身が入る、10回中8回。",
      reason: "言葉だけでクレートへ（来客・掃除・移動時に便利）。",
      testType: "trial",
      measure: { maxLatencySec: 3, trials: 10, successes: 8 },
      requires: ["crate:L1"],
    },
    {
      level: 3,
      condition: "中で落ち着いて留まらせる。",
      steps: [
        "「ハウス」で入らせる。",
        "入口のほうを向いて、その場に留まったら「Yes」→おやつ。",
      ],
      criterion: "入って向き直り、留まる、10回中8回。",
      reason: "中で落ち着いていられる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["crate:L2"],
    },
    {
      level: 4,
      condition: "離れた所から「ハウス」で送る。",
      steps: [
        "クレートから3m離れた所に立つ。",
        "「ハウス」と言う。",
        "近寄らず、まっすぐクレートへ入ったら「Yes」→中でおやつ。",
      ],
      criterion: "近寄らず直接クレートへ入る、10回中8回。",
      reason: "離れていても入れられる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["crate:L2"],
    },
    {
      level: 5,
      condition: "興奮させた直後でも「ハウス」。",
      steps: [
        "手を叩くなどで、少し興奮させる。",
        "すぐに「ハウス」と言う。",
        "興奮していても入ったら「Yes」→おやつ。",
      ],
      criterion: "興奮しても入る、10回中8回。",
      reason: "チャイムなどで興奮しても、自分の場所へ退避できる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["crate:L3"],
    },
  ],

  // ───────── 基本姿勢 ─────────
  sit: [
    {
      level: 1,
      condition: "おやつで誘導して座らせる（まだ言葉は言わない）。",
      steps: [
        "静かな部屋で、犬の鼻先におやつを近づける。",
        "おやつを頭の上をこえて後ろへゆっくり動かす。頭が上がると、自然におしりが下がる。",
        "おしりが床についた瞬間に「Yes」と言い、その姿勢のままおやつをあげる。まだ「おすわり」とは言わない。",
      ],
      criterion:
        "おやつの動きにつられて、おしりが床につく。これが5回続けてできれば合格（何秒かかってもOK）。",
      reason: "「座る」という体の動きを覚える、いちばん最初のステップ。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1"],
    },
    {
      level: 2,
      condition: "おやつを持たない手の合図だけで座らせる。",
      steps: [
        "おやつは持たず、Lv1と同じ「下から上へすくう」手の動きだけをする。",
        "その手の動きでおしりが床についたら「Yes」→反対の手に持ったおやつをあげる。",
        "言葉はまだ言わない。",
      ],
      criterion: "手の合図だけでおしりが床につく。10回中8回で合格（時間は問いません）。",
      reason: "おやつがなくても、手の合図で座れるようにする。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["sit:L1"],
    },
    {
      level: 3,
      condition: "「おすわり」と言ってから合図を出し、言葉を覚えさせる。",
      steps: [
        "先に「おすわり」と1回言う。",
        "そのすぐ後（1秒以内）に、いつもの手の合図を出す。",
        "座ったら「Yes」→おやつ。これをくり返すと、犬は「おすわり」が合図の予告だと覚えていく。",
      ],
      criterion:
        "10回くり返す。合図を出す前に座り始めることが10回中5回以上出てきたら、言葉が入ってきたサイン。",
      reason: "「おすわり」という言葉と、座る動きを結びつける（言葉を覚えるカギの段階）。",
      testType: "trial",
      measure: { trials: 10, successes: 5 },
      requires: ["sit:L2"],
    },
    {
      level: 4,
      condition: "言葉だけで座らせる（合図なし）。",
      steps: [
        "「おすわり」と1回だけ言う。",
        "手の合図は出さず、2〜3秒待つ。",
        "座ったら「Yes」→おやつ。座らなければLv3に戻り、ペアづけの回数を増やす。",
      ],
      criterion:
        "合図なし・言葉だけで、2秒以内に座る。10回中9回・言い直し0回で合格。ここで“言葉のおすわり”が完成します。",
      reason: "言葉だけで座れる＝「おすわり」を覚えた状態。日常で困らない基本ライン。",
      testType: "trial",
      measure: { noRepeatCue: true, maxLatencySec: 2, trials: 10, successes: 9 },
      requires: ["sit:L3"],
    },
    {
      level: 5,
      condition: "座った姿勢を3秒キープさせる。",
      steps: [
        "「おすわり」で座らせる。",
        "すぐ渡さず、心の中で3秒数える。",
        "3秒間おしりが床についたままなら「Yes」→おやつ。立ち上がったら、数える秒数を1秒に短くしてやり直す。",
      ],
      criterion: "おやつを渡すまでの3秒間、おしりを床から離さない。5回続けてできれば合格。",
      reason: "座った瞬間に立ち上がる“ピョン”を防ぐ（長く待たせる練習は「まて」で）。",
      testType: "duration",
      measure: { holdSeconds: 3, reps: 5, consecutive: true },
      requires: ["sit:L4"],
    },
    {
      level: 6,
      condition: "あなたが動いても座ったままにさせる。",
      steps: [
        "「おすわり」で座らせる。",
        "あなたがその場で立つ／横へ1歩動く／しゃがむ、のどれかをゆっくりやる。",
        "動いている間もおしりが床についたままなら「Yes」→おやつ。立ったら、動きを小さくしてやり直す。",
      ],
      criterion: "その動作の間、おしりを床から離さない。動作ごとに10回中8回で合格。",
      reason: "あなたの動きにつられて立ってしまわないようにする。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["sit:L5"],
    },
    {
      level: 7,
      condition: "床にある誘惑を無視して座らせる。",
      steps: [
        "犬にリードをつけ、おやつへ突進できないようにしておく。",
        "フード1粒を1m先の床に置く。犬が向かおうとしたら、先に「やめなさい」で止める。",
        "犬が落ち着いたら「おすわり」と言う。",
        "座れたら「Yes」→床のおやつではなく、手に持った別のおやつをあげる（床の物は取らせない）。",
        "慣れたら「やめなさい」を省き、「おすわり」だけで座れるようにする。",
      ],
      criterion: "おやつに向かわず、2秒以内に座る。10回中8回で合格。",
      reason: "目の前に誘惑があっても座れる。拾い食いの場面で安全。",
      testType: "trial",
      measure: { maxLatencySec: 2, trials: 10, successes: 8 },
      requires: ["sit:L4", "leave-it:L1"],
    },
    {
      level: 8,
      condition: "興奮させた直後に座らせる。",
      steps: [
        "おもちゃを目の前で軽く振る、または手を2回たたいて、少しだけ興奮させる。",
        "その直後に「おすわり」と言う。",
        "飛びつかず座れたら「Yes」→おやつ。飛びついたら、煽りを弱めてやり直す。",
      ],
      criterion: "飛びつかず、2秒以内に座る。10回中8回で合格。",
      reason: "興奮していても座れる。飛びつきの代わりになる行動。",
      testType: "trial",
      measure: { maxLatencySec: 2, trials: 10, successes: 8 },
      requires: ["sit:L4"],
    },
    {
      level: 9,
      condition: "離れた所から座らせる（室内）。",
      steps: [
        "安全な室内で、犬を落ち着かせてリードを外す。",
        "犬から3m離れて正面に立つ。",
        "「おすわり」と言う。近寄らずその場で座れたら「Yes」→近づいて、またはおやつを投げて渡す。",
      ],
      criterion: "近寄ってこず、その場で3秒以内に座る。10回中8回で合格。",
      reason: "離れていても止められる。道路へ走り出す前などの安全につながる。",
      testType: "trial",
      measure: { maxLatencySec: 3, trials: 10, successes: 8 },
      requires: ["sit:L4"],
    },
    {
      level: 10,
      condition: "静かな屋外で座らせる（場所を変えて）。",
      steps: [
        "人も犬もいない静かな屋外（自宅の外）に行く。",
        "「おすわり」と言い、座れたら「Yes」→おやつ。",
        "場所を変えて、ちがう3か所でできるようにする。",
      ],
      criterion: "場所を3か所変えて、それぞれ2秒以内に座る。各場所10回中8回で合格。",
      reason: "「家ではできるのに外でできない」を解消する。",
      testType: "trial",
      measure: { maxLatencySec: 2, places: 3, trials: 10, successes: 8 },
      requires: ["sit:L4"],
    },
    {
      level: 11,
      condition: "散歩中、歩きながら止めて座らせる。",
      steps: [
        "リードをつけて散歩する。",
        "歩いている途中で立ち止まり、「おすわり」と言う。",
        "すぐ座れたら「Yes」→おやつ→また歩き出す。これを1回の散歩で5か所やる。",
      ],
      criterion: "1回の散歩で5か所、立ち止まってすぐ（3秒以内）に座れれば合格。",
      reason: "横断歩道の前などで座って待てる＝交通安全。",
      testType: "tally",
      measure: { places: 5, successes: 5, maxLatencySec: 3 },
      requires: ["sit:L10", "loose-leash:L1"],
    },
    {
      level: 12,
      condition: "人や犬がいる公園で座らせる。",
      steps: [
        "人や犬がいる公園に、リードをつけて行く。",
        "まわりに刺激がある状態で「おすわり」と言う。",
        "座れたら「Yes」→おやつ。できなければ、刺激から少し離れてやり直す。",
      ],
      criterion: "まわりに人や犬がいても、3秒以内に座る。10回中8回で合格。",
      reason: "どんな場所・刺激でも座れる、いちばんの仕上げ。",
      testType: "tally",
      measure: { maxLatencySec: 3, trials: 10, successes: 8 },
      requires: ["sit:L8", "sit:L10"],
    },
  ],

  down: [
    {
      level: 1,
      condition: "おやつで誘導して伏せさせる（まだ言葉は言わない）。",
      steps: [
        "静かな部屋で、犬の鼻先におやつを近づける。",
        "おやつを鼻先からまっすぐ下、床へゆっくり下ろす。鼻を追って、ひじと胸が床につく。",
        "ついた瞬間に「Yes」→その姿勢のままおやつ。まだ「ふせ」とは言わない。",
      ],
      criterion: "おやつにつられて、ひじと胸が床につく。5回続けてできれば合格（時間はかかってOK）。",
      reason: "「伏せる」体の動きを覚える、最初のステップ。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["sit:L1"],
    },
    {
      level: 2,
      condition: "おやつを持たない手の合図だけで伏せさせる。",
      steps: [
        "おやつは持たず、Lv1と同じ「床へ下ろす」手の動きだけをする。",
        "ひじと胸が床についたら「Yes」→反対の手に持ったおやつ。",
        "言葉はまだ言わない。",
      ],
      criterion: "手の合図だけで伏せる、10回中8回（時間は問いません）。",
      reason: "おやつがなくても、合図で伏せられるようにする。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["down:L1"],
    },
    {
      level: 3,
      condition: "「ふせ」と言ってから合図を出し、言葉を覚えさせる。",
      steps: [
        "先に「ふせ」と1回言う。",
        "そのすぐ後に、床へ下ろす手の合図を出す。",
        "伏せたら「Yes」→おやつ。くり返すと「ふせ」が合図の予告だと覚える。",
      ],
      criterion:
        "10回くり返す。合図を出す前に伏せ始めることが10回中5回以上出てきたら、言葉が入ったサイン。",
      reason: "「ふせ」という言葉と、伏せる動きを結びつける（言葉を覚えるカギの段階）。",
      testType: "trial",
      measure: { trials: 10, successes: 5 },
      requires: ["down:L2"],
    },
    {
      level: 4,
      condition: "言葉だけで伏せさせる（合図なし）。",
      steps: [
        "「ふせ」と1回だけ言う。",
        "手の合図は出さず、2〜3秒待つ。",
        "伏せたら「Yes」→おやつ。伏せなければLv3に戻り、ペアづけを増やす。",
      ],
      criterion:
        "言葉だけで、2秒以内に伏せる。10回中9回・言い直し0回で合格。ここで“言葉のふせ”が完成。",
      reason: "言葉だけで伏せる＝「ふせ」を覚えた状態。日常で困らない基本ライン。",
      testType: "trial",
      measure: { noRepeatCue: true, maxLatencySec: 2, trials: 10, successes: 9 },
      requires: ["down:L3"],
    },
    {
      level: 5,
      condition: "立った状態から、直接伏せさせる。",
      steps: [
        "犬が立っている状態で「ふせ」と言う（座らせない）。",
        "立った姿勢からそのまま伏せたら「Yes」→おやつ。",
        "できなければ、おやつを床へ下ろす誘導を少し足してやり直す。",
      ],
      criterion: "立ったまま、すぐ伏せる、10回中8回。",
      reason: "とっさのときの素早い静止に使える。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["down:L4"],
    },
    {
      level: 6,
      condition: "軽い誘惑がある中で伏せさせる。",
      steps: [
        "犬にリードをつける。1m先の床におやつを置く、またはあなたが少し動く。",
        "誘惑があっても「ふせ」と言う。向かおうとしたら「やめなさい」で止める。",
        "伏せたら「Yes」→手持ちの別のおやつ（床の物は取らせない）。",
      ],
      criterion: "誘惑に向かわず伏せる、10回中8回。",
      reason: "気が散る状況でも伏せられる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["down:L4", "leave-it:L1"],
    },
    {
      level: 7,
      condition: "離れた所から伏せさせる。",
      steps: [
        "犬を落ち着かせ、3m離れて正面に立つ。",
        "「ふせ」と言う。",
        "近寄らずその場で伏せたら「Yes」→近づいて、または投げて渡す。",
      ],
      criterion: "近寄らず、その場で伏せる、10回中8回。",
      reason: "離れていても伏せさせられる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["down:L4"],
    },
    {
      level: 8,
      condition: "静かな屋外で伏せさせる（場所を変えて）。",
      steps: [
        "人も犬もいない静かな屋外に行く。",
        "「ふせ」と言い、伏せたら「Yes」→おやつ。",
        "場所を変えて、ちがう3か所でできるようにする。",
      ],
      criterion: "各場所で伏せる、各10回中8回。",
      reason: "外でも通じる。",
      testType: "trial",
      measure: { places: 3, trials: 10, successes: 8 },
      requires: ["down:L4"],
    },
    {
      level: 9,
      condition: "人や犬がいる公園で伏せさせる。",
      steps: [
        "人や犬がいる公園に、リードをつけて行く。",
        "刺激がある中で「ふせ」と言う。",
        "伏せたら「Yes」→おやつ。できなければ刺激から少し離れてやり直す。",
      ],
      criterion: "機会10回中、伏せるのが8回以上。",
      reason: "カフェ・電車など、落ち着いて待つ場面の核。",
      testType: "tally",
      measure: { trials: 10, successes: 8 },
      requires: ["down:L8"],
    },
  ],

  stand: [
    {
      level: 1,
      condition: "おやつで誘導して立たせる（まだ言葉は言わない）。",
      steps: [
        "犬を座らせる。鼻先におやつを近づける。",
        "おやつを鼻先からまっすぐ前へ動かす。前へ出ようとして4本足で立つ。",
        "立った瞬間に「Yes」→その姿勢のままおやつ。まだ「たて」とは言わない。",
      ],
      criterion: "おやつにつられて4本足で立ち、歩き出さない。5回続けてできれば合格。",
      reason: "「立つ」姿勢を覚える、最初のステップ。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["sit:L1"],
    },
    {
      level: 2,
      condition: "おやつを持たない手の合図だけで立たせる。",
      steps: [
        "おやつは持たず、Lv1と同じ「前へ動かす」手の動きだけをする。",
        "立ったら「Yes」→反対の手に持ったおやつ。",
        "言葉はまだ言わない。",
      ],
      criterion: "手の合図だけで立つ、10回中8回。",
      reason: "おやつがなくても、合図で立てるようにする。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["stand:L1"],
    },
    {
      level: 3,
      condition: "「たて」と言ってから合図を出し、言葉を覚えさせる。",
      steps: [
        "先に「たて」と1回言う。",
        "そのすぐ後に、前へ動かす手の合図を出す。",
        "立ったら「Yes」→おやつ。くり返して言葉を覚えさせる。",
      ],
      criterion: "10回くり返す。合図を出す前に立ち始めるのが10回中5回以上で、言葉が入ったサイン。",
      reason: "「たて」という言葉と、立つ動きを結びつける。",
      testType: "trial",
      measure: { trials: 10, successes: 5 },
      requires: ["stand:L2"],
    },
    {
      level: 4,
      condition: "言葉だけで立たせる（合図なし）。",
      steps: [
        "「たて」と1回だけ言う。",
        "手の合図は出さず、2〜3秒待つ。",
        "立ったら「Yes」→おやつ。立たなければLv3に戻る。",
      ],
      criterion:
        "言葉だけで2秒以内に立つ、10回中9回・言い直し0回で合格。ここで“言葉のたて”が完成。",
      reason: "言葉だけで立つ＝「たて」を覚えた状態。",
      testType: "trial",
      measure: { noRepeatCue: true, maxLatencySec: 2, trials: 10, successes: 9 },
      requires: ["stand:L3"],
    },
    {
      level: 5,
      condition: "立った姿勢を2秒キープさせる。",
      steps: [
        "「たて」で立たせる。",
        "すぐ渡さず、2秒数える。",
        "2秒間動かず立っていられたら「Yes」→おやつ。歩き出したら1秒に短くしてやり直す。",
      ],
      criterion: "動かず2秒間立っていられる、5回続けて。",
      reason: "診察やお手入れの基本姿勢。",
      testType: "duration",
      measure: { holdSeconds: 2, reps: 5, consecutive: true },
      requires: ["stand:L4"],
    },
    {
      level: 6,
      condition: "立ったまま、体を撫でさせる。",
      steps: [
        "「たて」で立たせる。",
        "立っている間に、背中やお腹をやさしく撫でる。",
        "撫でても立ったままなら「Yes」→おやつ。動いたら、触る時間を短くしてやり直す。",
      ],
      criterion: "撫でられても立ったまま、10回中8回。",
      reason: "健康チェックやタオル拭きが楽になる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["stand:L5"],
    },
  ],

  // ───────── 静止・位置 ─────────
  stay: [
    {
      level: 1,
      condition: "「まて」で短く待たせ、「ブレイク」で解放する。",
      steps: [
        "犬を座らせる（または伏せ）。「まて」と言う。",
        "1秒たったら、終わりの合図「ブレイク」と言って犬を動かす。",
        "ブレイクの言葉まで動かなければ「Yes」→おやつ。",
      ],
      criterion: "終わりの合図まで動かない、5回続けて。",
      reason: "「終わりの合図まで待つ」を覚える、まての土台。",
      testType: "duration",
      measure: { successes: 5, consecutive: true },
      requires: ["sit:L4", "release:L1"],
    },
    {
      level: 2,
      condition: "待つ時間を10秒にのばす。",
      steps: [
        "「まて」と言う。",
        "心の中で10秒数える。",
        "10秒間、姿勢を崩さず待てたら「ブレイク」→「Yes」→おやつ。崩れたら秒数を短くしてやり直す。",
      ],
      criterion: "終わりの合図まで10秒、姿勢を保つ、5回続けて。",
      reason: "待てる時間を増やす。",
      testType: "duration",
      measure: { holdSeconds: 10, reps: 5, consecutive: true },
      requires: ["stay:L1"],
    },
    {
      level: 3,
      condition: "待つ時間を30秒にのばす。",
      steps: [
        "「まて」と言う。",
        "30秒数える。",
        "30秒待てたら「ブレイク」→「Yes」→おやつ。",
      ],
      criterion: "終わりの合図まで30秒、姿勢を保つ、5回続けて。",
      reason: "食事中・玄関対応に使える長さ。",
      testType: "duration",
      measure: { holdSeconds: 30, reps: 5, consecutive: true },
      requires: ["stay:L2"],
    },
    {
      level: 4,
      condition: "あなたが1歩離れても待たせる。",
      steps: [
        "「まて」と言う。",
        "その場で1歩下がって、すぐ戻る。",
        "動かず待てていたら「ブレイク」→「Yes」→おやつ。",
      ],
      criterion: "1歩下がって戻る間、待てる、10回中8回。",
      reason: "あなたが離れても待てる（距離の始まり）。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["stay:L3"],
    },
    {
      level: 5,
      condition: "あなたが3m離れても待たせる。",
      steps: [
        "「まて」と言う。",
        "3m離れて、3秒待ってから戻る。",
        "動かず待てていたら「ブレイク」→「Yes」→おやつ。",
      ],
      criterion: "3m離れて戻る間、待てる、10回中8回。",
      reason: "もっと離れても待てる。",
      testType: "trial",
      measure: { holdSeconds: 3, trials: 10, successes: 8 },
      requires: ["stay:L4"],
    },
    {
      level: 6,
      condition: "あなたが見えなくなっても待たせる。",
      steps: [
        "「まて」と言う。",
        "部屋を出て、5秒たってから戻る。",
        "戻ったときも待てていたら「ブレイク」→「Yes」→おやつ。",
      ],
      criterion: "部屋を出て戻った時も待てている、10回中8回。",
      reason: "見えなくても待てる（留守番・来客の土台）。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["stay:L5"],
    },
    {
      level: 7,
      condition: "おやつの誘惑がある中で待たせる。",
      steps: [
        "「まて」と言う。",
        "1m先の床におやつを置く。",
        "取りに行かず15秒待てたら「ブレイク」→「Yes」→手持ちの別のおやつ（床の物は取らせない）。",
      ],
      criterion: "取らずに15秒待てる、10回中8回。",
      reason: "誘惑があっても待てる。",
      testType: "duration",
      measure: { holdSeconds: 15, trials: 10, successes: 8 },
      requires: ["stay:L3", "leave-it:L2"],
    },
    {
      level: 8,
      condition: "玄関ドアを開けても飛び出さず待たせる。",
      steps: [
        "玄関で「まて」と言う。",
        "ドアを開ける。犬が出ようとしたら、いったん閉めてやり直す。",
        "飛び出さず3秒待てたら「ブレイク」と言って一緒に出る。",
      ],
      criterion: "ドアを開けても飛び出さず3秒待ち、合図で出る、10回中9回。",
      reason: "脱走を防ぐ＝命を守る、まての本番。",
      testType: "trial",
      measure: { holdSeconds: 3, trials: 10, successes: 9 },
      requires: ["stay:L5"],
    },
    {
      level: 9,
      condition: "人や犬がいる公園で待たせる。",
      steps: [
        "公園で「まて」と言う。",
        "30秒待たせる。",
        "待てたら「ブレイク」→「Yes」→おやつ。できなければ刺激から少し離れてやり直す。",
      ],
      criterion: "30秒待てる、10回中7回。",
      reason: "どこでも待てる、いちばんの仕上げ。",
      testType: "duration",
      measure: { holdSeconds: 30, trials: 10, successes: 7 },
      requires: ["stay:L6", "stay:L8"],
    },
  ],

  // 待って（任意）＝姿勢は問わず“次の合図まで一瞬止まる”。stayの簡易版。
  wait: [
    {
      level: 1,
      condition: "ドアの前で一瞬待たせる。",
      steps: [
        "犬を連れてドアの前に立ち、「待って」と言う。",
        "ドアノブに手をかける。犬が前に出ようとしたら、手を止める（ドアは開けない）。",
        "犬が控えたら「Yes」→「ブレイク」でドアを通す。",
      ],
      criterion: "前進をやめて控える、10回中8回。",
      reason: "ドアからの突進を止める（脱走・飛び出し予防）。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["marker:L1", "release:L1"],
    },
    {
      level: 2,
      condition: "ドアを少し開けても待たせる。",
      steps: [
        "「待って」と言って、ドアを少しだけ開ける。",
        "犬が出ようとしたら、すぐ閉める。",
        "飛び出さず待てたら「Yes」→「ブレイク」で通す。",
      ],
      criterion: "飛び出さない、10回中8回。",
      reason: "開いても出ない一時停止。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["wait:L1"],
    },
    {
      level: 3,
      condition: "食器を置く間、待たせる。",
      steps: [
        "ごはんを持って「待って」と言う。",
        "食器を床に置く。犬が突進したら、食器を持ち上げてやり直す。",
        "待てたら「ブレイク」と言って食べさせる。",
      ],
      criterion: "食器へ突進せず待つ、10回中8回。",
      reason: "食事の興奮をコントロール。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["wait:L1"],
    },
    {
      level: 4,
      condition: "散歩中、段差・縁石の前で待たせる。",
      steps: [
        "散歩中、段差や縁石の手前で立ち止まり「待って」。",
        "犬も立ち止まったら「Yes」。",
        "安全を確認して「ブレイク」で進む。",
      ],
      criterion: "立ち止まる、10回中8回。",
      reason: "横断・段差の前で止まる安全習慣。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["wait:L2", "loose-leash:L1"],
    },
    {
      level: 5,
      condition: "車のドアを開けても待たせる。",
      steps: [
        "車の中の犬に「待って」と言う。",
        "ドアを開ける。降りようとしたら閉めてやり直す。",
        "飛び降りず待てたら「ブレイク」で降ろす。",
      ],
      criterion: "飛び降りずに待つ、10回中8回。",
      reason: "乗り降りのときの飛び出し防止（交通安全）。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["wait:L2"],
    },
  ],

  place: [
    {
      level: 1,
      condition: "マットにおやつで誘導して乗せる。",
      steps: [
        "床に専用マット（タオルやベッドでOK）を置く。",
        "おやつをマットの上に投げて、犬を乗せる。",
        "4本足がマットに乗った瞬間に「Yes」→マットの上でおやつ。",
      ],
      criterion: "4本足がマットに乗る、5回続けて。",
      reason: "「自分の場所（持ち運べるマット）」を覚える。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["down:L1", "stay:L1", "release:L1"],
    },
    {
      level: 2,
      condition: "「プレイス」でマットへ行かせる。",
      steps: [
        "マットを指さしながら「プレイス」と1回言う。",
        "犬がマットに乗ったら「Yes」→マットの上でおやつ。",
        "おやつの投げ込みは少しずつ減らす。",
      ],
      criterion: "マットへ行って乗る、10回中8回。",
      reason: "言葉でマットへ行けるようにする。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["place:L1"],
    },
    {
      level: 3,
      condition: "マットの上で伏せて待たせる。",
      steps: [
        "「プレイス」でマットに乗せ、「ふせ」で伏せさせる。",
        "「まて」で10秒待たせる。",
        "崩さず待てたら「ブレイク」→「Yes」→おやつ。",
      ],
      criterion: "マット上で伏せたまま10秒、10回中8回。",
      reason: "自分の場所で落ち着いて留まる。",
      testType: "duration",
      measure: { holdSeconds: 10, trials: 10, successes: 8 },
      requires: ["place:L2", "stay:L2"],
    },
    {
      level: 4,
      condition: "離れた所から「プレイス」で送る。",
      steps: [
        "マットから3m離れた所に立つ。",
        "マットを指さして「プレイス」と言う。",
        "犬がまっすぐマットへ行ったら「Yes」→マットの上でおやつ。",
      ],
      criterion: "直接マットへ行く、10回中8回。",
      reason: "来客時など「あっちのマットで待ってて」が言える。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["place:L2"],
    },
    {
      level: 5,
      condition: "あなたが活動する間、マットで待たせる。",
      steps: [
        "「プレイス」でマットに乗せ、伏せさせる。",
        "あなたは家事や食事など、普通の活動をする。",
        "1分間マットから出なければ「ブレイク」→「Yes」→おやつ。出たら時間を短くしてやり直す。",
      ],
      criterion: "立ち上がらず1分間マット上で待つ、5回続けて。",
      reason: "食事中・作業中も、足元に来ず落ち着いて待てる。",
      testType: "duration",
      measure: { holdSeconds: 60, reps: 5, consecutive: true },
      requires: ["place:L3"],
    },
    {
      level: 6,
      condition: "興奮させた直後でもマットへ行かせる。",
      steps: [
        "手を叩くなどで、少し興奮させる。",
        "すぐに「プレイス」と言う。",
        "興奮していてもマットへ行けたら「Yes」→おやつ。",
      ],
      criterion: "興奮源があってもマットへ行く、10回中8回。",
      reason: "チャイムなどで興奮しても、自分の場所へ退避できる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["place:L2"],
    },
  ],

  settle: [
    {
      level: 1,
      condition: "自分からリラックスした瞬間をほめる。",
      steps: [
        "犬がマットや床で、腰を傾けてゴロンと寝そべるのを待つ。",
        "その瞬間に静かに「Yes」→そっとおやつを置く（興奮させない）。",
        "これをくり返して、リラックス姿勢を増やす。",
      ],
      criterion: "リラックス姿勢（腰を倒す）を5回ほめられる。",
      reason: "「力を抜く」を教える土台。",
      testType: "trial",
      measure: { successes: 5 },
      requires: ["down:L1", "place:L1"],
    },
    {
      level: 2,
      condition: "「落ち着いて」でリラックスさせる。",
      steps: [
        "マットの上で「ふせ」をさせる。",
        "「落ち着いて」と静かに言い、腰を倒すのを待つ。",
        "腰を倒したら「Yes」→そっとおやつ。",
      ],
      criterion: "号令でリラックス姿勢を取る、10回中8回。",
      reason: "言葉で落ち着かせられるようにする。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["settle:L1"],
    },
    {
      level: 3,
      condition: "リラックスを30秒保たせる。",
      steps: [
        "「落ち着いて」でリラックスさせる。",
        "30秒、静かに待つ（声をかけすぎない）。",
        "腰を倒したまま30秒たてたら、そっとおやつ。",
      ],
      criterion: "腰を倒したまま30秒、5回続けて。",
      reason: "落ち着きを長く保てるようにする。",
      testType: "duration",
      measure: { holdSeconds: 30, reps: 5, consecutive: true },
      requires: ["settle:L2"],
    },
    {
      level: 4,
      condition: "リラックスを2分保たせる。",
      steps: [
        "「落ち着いて」でリラックスさせる。",
        "2分間、静かに過ごさせる。",
        "保てたら、そっとおやつ。",
      ],
      criterion: "2分間リラックスを保つ、3回。",
      reason: "カフェや待合室で落ち着ける。",
      testType: "duration",
      measure: { holdSeconds: 120, reps: 3 },
      requires: ["settle:L3"],
    },
    {
      level: 5,
      condition: "生活音がある中でリラックスを保たせる。",
      steps: [
        "「落ち着いて」でリラックスさせる。",
        "食器を動かす・テレビをつけるなど、普段の生活音を出す。",
        "音があっても2分保てたら、そっとおやつ。",
      ],
      criterion: "生活音の中で2分間保つ、10回中8回。",
      reason: "家の中の音で乱れない。",
      testType: "duration",
      measure: { holdSeconds: 120, trials: 10, successes: 8 },
      requires: ["settle:L4"],
    },
    {
      level: 6,
      condition: "外のベンチでリラックスさせる。",
      steps: [
        "自宅の外の静かなベンチに座り、足元で「落ち着いて」。",
        "1分間、落ち着いていられたら、そっとおやつ。",
        "別の場所でも試す。",
      ],
      criterion: "ちがう2か所で、各1分間リラックスを保つ。",
      reason: "外出先でも落ち着ける（行動範囲が広がる）。",
      testType: "duration",
      measure: { places: 2, holdSeconds: 60 },
      requires: ["settle:L4"],
    },
  ],

  // ───────── 呼び戻し ─────────
  come: [
    {
      level: 1,
      condition: "近くで「おいで」を覚えさせる。",
      steps: [
        "犬から1〜2m離れてしゃがみ、明るい声で名前＋「おいで」と言う。",
        "来たら、まず首輪をやさしくつかんでから「Yes」→おやつ。",
        "「おいで＝必ず良いこと、つかまれても平気」をくり返す。",
      ],
      criterion: "来て、首輪をつかませる、5回続けて。",
      reason: "「おいで＝必ず良いこと」＋つかまれても逃げない、を作る。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1", "name-response:L1"],
    },
    {
      level: 2,
      condition: "部屋の中で5m離れて呼ぶ。",
      steps: [
        "部屋の中で5m離れる。",
        "名前＋「おいで」と1回言う。",
        "3秒以内に来て正面まで来たら、首輪をつかんで「Yes」→おやつ。",
      ],
      criterion: "3秒以内に来て正面まで来る、10回中9回。",
      reason: "きちんと戻る。",
      testType: "trial",
      measure: { maxLatencySec: 3, trials: 10, successes: 9 },
      requires: ["come:L1"],
    },
    {
      level: 3,
      condition: "見えない所から呼ぶ。",
      steps: [
        "別の部屋（姿が見えない所）へ行く。",
        "名前＋「おいで」と言う。",
        "来たら「Yes」→おやつ。",
      ],
      criterion: "来る、10回中8回。",
      reason: "見えなくても戻る。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["come:L2"],
    },
    {
      level: 4,
      condition: "おもちゃの誘惑を無視して来させる。",
      steps: [
        "床におもちゃを置く。",
        "少し離れて「おいで」と言う。",
        "おもちゃに行かず来たら「Yes」→おやつ。行こうとしたら「やめなさい」で止める。",
      ],
      criterion: "おもちゃを無視して来る、10回中8回。",
      reason: "誘惑をふり切って戻る。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["come:L2", "leave-it:L2"],
    },
    {
      level: 5,
      condition: "屋外で（ロングライン）呼ぶ。",
      steps: [
        "安全な屋外で、5mのロングライン（長いリード）をつける。",
        "5m離れて「おいで」と言う。",
        "来たら「Yes」→おやつ。ちがう2か所で試す。",
      ],
      criterion: "各場所で来る、各10回中8回。",
      reason: "外でも戻る。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["come:L2"],
    },
    {
      level: 6,
      condition: "遊びに夢中な最中に呼ぶ。",
      steps: [
        "少しおもちゃで遊ばせて、夢中にさせる。",
        "遊びを中断して「おいで」と言う。",
        "来たら大げさにほめて「Yes」→おやつ→また遊んでよい。",
      ],
      criterion: "夢中の最中でも来る、10回中7回。",
      reason: "夢中でも戻る＝本当の安全。",
      testType: "trial",
      measure: { trials: 10, successes: 7 },
      requires: ["come:L5"],
    },
    {
      level: 7,
      condition: "公園（人や犬がいる）で呼ぶ。",
      steps: [
        "人や犬がいる公園で、ロングラインをつける。",
        "「おいで」と言う。",
        "来たら「Yes」→特別に良いおやつ。来なければ刺激から少し離れてやり直す。",
      ],
      criterion: "機会10回中、来るのが7回以上。",
      reason: "刺激の中でも戻る。",
      testType: "tally",
      measure: { trials: 10, successes: 7 },
      requires: ["come:L6"],
    },
    {
      level: 8,
      condition: "緊急用の特別な合図を覚えさせる。",
      steps: [
        "普段使わない専用の合図（笛や特別な言葉）を決める。",
        "その合図のあと、最高のごほうび（大量のおやつ・大好きな遊び）を必ず出す。安全な場所でくり返し、合図＝最高、を刷り込む。",
        "本番（道路への飛び出しなど）以外では絶対に乱用しない。",
      ],
      criterion: "合図で全力で戻る、5回中5回。",
      reason: "道路への飛び出しなど、一度きりの本番で確実に止める。",
      testType: "trial",
      measure: { trials: 5, successes: 5 },
      requires: ["come:L7"],
    },
  ],

  // ───────── 衝動制御 ─────────
  "leave-it": [
    {
      level: 1,
      condition: "にぎった手の中のおやつを我慢させる。",
      steps: [
        "おやつをにぎった手を、犬の前に出す（手は開かない）。",
        "犬がなめたり噛んだりしても手を開かない。あきらめて鼻を離し、あなたを見た瞬間に「Yes」→にぎっていない手から“別の”おやつをあげる。",
        "手の中のおやつは、絶対にあげない。",
      ],
      criterion: "鼻を離して見る、5回続けて。",
      reason: "「我慢するともっと良いことがある」を教える。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1"],
    },
    {
      level: 2,
      condition: "「やめなさい」で床のおやつから離れさせる。",
      steps: [
        "床におやつを置き、すぐ手で覆える状態にする。",
        "「やめなさい」と言う。犬が取ろうとしたら、手で覆って守る。",
        "おやつから離れてあなたを見たら「Yes」→別のおやつ。",
      ],
      criterion: "号令でおやつから離れて、あなたを見る、10回中8回。",
      reason: "言葉で「それには関わらない」を伝える。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["leave-it:L1"],
    },
    {
      level: 3,
      condition: "覆わない床のおやつで「やめなさい」。",
      steps: [
        "床におやつを置く（手は覆わないが、いつでも覆えるよう構える）。",
        "「やめなさい」と言う。",
        "取らずに離れたら「Yes」→別のおやつ。取ろうとしたら手で隠す。",
      ],
      criterion: "取らずに離れる、10回中8回。",
      reason: "落ちている物を食べない＝拾い食い・誤飲を防ぐ。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["leave-it:L2"],
    },
    {
      level: 4,
      condition: "もっと欲しい物で「やめなさい」。",
      steps: [
        "人の食べ物のにおいがする物など、価値の高い物を床に置く。",
        "「やめなさい」と言う。",
        "取らずに離れたら「Yes」→特別に良いおやつ。",
      ],
      criterion: "取らずに離れる、10回中8回。",
      reason: "強い誘惑でも我慢できる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["leave-it:L3"],
    },
    {
      level: 5,
      condition: "またいで歩く間「やめなさい」。",
      steps: [
        "床におやつを置く。",
        "「やめなさい」と言いながら、その上をまたいで一緒に歩く。",
        "取らずに通り過ぎたら「Yes」→別のおやつ。",
      ],
      criterion: "取らずに通り過ぎる、10回中8回。",
      reason: "通り道に落ちていても我慢する。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["leave-it:L3"],
    },
    {
      level: 6,
      condition: "散歩中の落ちている物で「やめなさい」。",
      steps: [
        "散歩前に、道に安全な物（おやつ等）をいくつか置いておく。",
        "通りかかったら「やめなさい」。",
        "取らずに通過できたら「Yes」→おやつ。5か所でできれば合格。",
      ],
      criterion: "5か所、取らずに通過できれば合格。",
      reason: "散歩中の拾い食いを防ぐ（安全）。",
      testType: "tally",
      measure: { places: 5, successes: 5 },
      requires: ["leave-it:L4"],
    },
    {
      level: 7,
      condition: "動く誘惑で「やめなさい」。",
      steps: [
        "おやつやおもちゃを、犬の前で転がす。",
        "転がす前か同時に「やめなさい」と言う。",
        "追いかけなければ「Yes」→別のおやつ。",
      ],
      criterion: "追いかけない、10回中8回。",
      reason: "猫や自転車など、動く物に飛び出さない。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["leave-it:L4"],
    },
  ],

  "drop-it": [
    {
      level: 1,
      condition: "交換で「出して」を覚えさせる。",
      steps: [
        "犬がおもちゃをくわえているとき、別の良いおやつを鼻先に見せる。",
        "犬がおもちゃを放したら「Yes」→おやつをあげ、おもちゃも返す。",
        "放す動きが安定したら、放す直前に「出して」と言葉を添える。",
      ],
      criterion: "放す、5回続けて。",
      reason: "「交換するともっと良いことがある」を教える。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1"],
    },
    {
      level: 2,
      condition: "言葉だけで「出して」。",
      steps: [
        "交換のおやつを見せずに「出して」と1回言う。",
        "2秒以内に放したら「Yes」→おやつ＋おもちゃを返す。",
      ],
      criterion: "2秒以内に放す、10回中8回。",
      reason: "言葉だけで放せるようにする。",
      testType: "trial",
      measure: { maxLatencySec: 2, trials: 10, successes: 8 },
      requires: ["drop-it:L1"],
    },
    {
      level: 3,
      condition: "大事な物で「出して」。",
      steps: [
        "お気に入りのおもちゃや骨など、放したくない物で「出して」。",
        "放したら「Yes」→特別に良いおやつ＋返す。",
      ],
      criterion: "放す、10回中8回。",
      reason: "大事な物でも放す＝危険物・誤飲のとき安全。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["drop-it:L2"],
    },
    {
      level: 4,
      condition: "散歩中に拾った物を「出して」。",
      steps: [
        "散歩前に、安全な物を道に置いておく。",
        "犬がくわえたら「出して」。",
        "飲み込む前に放せたら「Yes」→おやつ。5回できれば合格。",
      ],
      criterion: "5回、飲み込む前に放せる。",
      reason: "拾い食いしても、その場で出させられる。",
      testType: "tally",
      measure: { successes: 5 },
      requires: ["drop-it:L3"],
    },
    {
      level: 5,
      condition: "引っ張りっこ中に「出して」。",
      steps: [
        "おもちゃで引っ張りっこをする。",
        "途中で「出して」と言う。",
        "放したら「Yes」→すぐまた引っ張りっこを再開（遊びがごほうび）。",
      ],
      criterion: "放す、10回中8回。",
      reason: "興奮していても放せる＝遊びの安全。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["drop-it:L3"],
    },
  ],

  // オフ＝乗っている/前足をかけた状態から「降ろす・離す」受動アクションのみ
  off: [
    {
      level: 1,
      condition: "おやつで誘導して降りさせる。",
      steps: [
        "犬をソファなどに乗せる。",
        "おやつを床のほうへ動かして「オフ」と言い、降りるよう誘導する。",
        "床に4本足で降りたら「Yes」→おやつ。",
      ],
      criterion: "床に4本足で降りる、5回続けて。",
      reason: "「降りる」を覚える。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1"],
    },
    {
      level: 2,
      condition: "言葉だけで降りさせる。",
      steps: [
        "犬がソファに乗った状態で、誘導せず「オフ」と1回言う。",
        "2秒以内に床へ降りたら「Yes」→おやつ。",
      ],
      criterion: "2秒以内に床へ降りる、10回中8回。",
      reason: "言葉だけで家具から降ろせる。",
      testType: "trial",
      measure: { maxLatencySec: 2, trials: 10, successes: 8 },
      requires: ["off:L1"],
    },
    {
      level: 3,
      condition: "前足を下ろさせる。",
      steps: [
        "犬に、あなたのひざへ前足をかけさせる。",
        "「オフ」と言う。",
        "前足を床に下ろしたら「Yes」→おやつ。",
      ],
      criterion: "前足を下ろす、10回中8回。",
      reason: "人に前足をかけたとき、離させる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["off:L2"],
    },
  ],

  // 飛びつかない挨拶＝そもそも飛びつかないデフォルト行動（号令で出すものではない）
  "polite-greeting": [
    {
      level: 1,
      condition: "落ち着いた出迎えを作る。",
      steps: [
        "あなたが静かに犬へ近づく（あいさつの場面を作る）。",
        "犬が飛びつかず、4本足のまま／座ったままでいられたら「Yes」→おやつ。",
        "飛びついたら、何も言わず体を背ける（注目を外す）。",
      ],
      criterion: "飛びつかず、4本足／座ったまま、10回中8回。",
      reason: "落ち着いた出迎えを“ふつう”にする。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["sit:L4"],
    },
    {
      level: 2,
      condition: "興奮させても飛びつかせない。",
      steps: [
        "手を叩く・しゃがむなどで、少し興奮させる。",
        "飛びつかなければ「Yes」→おやつ。",
        "飛びついたら「オフ」で前足を下ろさせ、その回は失敗としてやり直す。",
      ],
      criterion: "飛びつかない、10回中8回（飛びついたら「オフ」で下ろす＝その回は失敗）。",
      reason: "興奮させられても飛びつかない。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["polite-greeting:L1", "off:L2"],
    },
    {
      level: 3,
      condition: "散歩中、人とすれ違っても飛びつかせない。",
      steps: [
        "散歩中、通行人とすれ違う場面で、犬を自分の横につけておく。",
        "飛びつかずにすれ違えたら「Yes」→おやつ。",
        "すれ違いの機会を10回数え、飛びつき0が8回以上で合格。",
      ],
      criterion: "すれ違い10回のうち、飛びつき0が8回以上。",
      reason: "他人に飛びつかない（社会的信頼・安全）。",
      testType: "tally",
      measure: { trials: 10, successes: 8 },
      requires: ["polite-greeting:L2"],
    },
  ],

  // ───────── 歩行 ─────────
  "loose-leash": [
    {
      level: 1,
      condition: "「たるんだら進む」を教える。",
      steps: [
        "室内か庭で、リードを短めに持って歩く。",
        "リードがピンと張ったら、その場でピタッと止まる（引っ張り返さない）。",
        "犬がこちらを見る・近づいてリードがたるんだら、ほめて歩き出す。たるんだまま3歩進めればOK。",
      ],
      criterion: "リードがたるんだまま3歩進む、5回。",
      reason: "「ゆるめれば進める・引っ張ると止まる」を教える。",
      testType: "trial",
      measure: { overSteps: 3, reps: 5, successes: 5 },
      requires: ["marker:L1", "name-response:L1"],
    },
    {
      level: 2,
      condition: "続けて歩けるようにする。",
      steps: [
        "L1と同じ「張ったら止まる・たるんだら進む」で歩く。",
        "止まる回数を減らし、続けて歩く。",
        "リードを張らずに10歩続けて歩ければOK。",
      ],
      criterion: "リードを張らずに10歩連続、5回続けて。",
      reason: "止まらず続けて歩ける。",
      testType: "trial",
      measure: { overSteps: 10, successes: 5, consecutive: true },
      requires: ["loose-leash:L1"],
    },
    {
      level: 3,
      condition: "方向転換でも張らせない。",
      steps: [
        "歩きながら、左右に向きを変える。",
        "向きを変えるとき、犬もついてくるよう、声で誘導する。",
        "転換のときにリードが張らなければOK。",
      ],
      criterion: "転換時に張らない、10回中8回。",
      reason: "向きを変えても引っ張らない。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["loose-leash:L2"],
    },
    {
      level: 4,
      condition: "静かな道で歩く。",
      steps: [
        "自宅前の静かな道へ出る。",
        "「張ったら止まる」を続けながら歩く。",
        "一度も張らずに20歩歩ければOK。",
      ],
      criterion: "張り0で20歩、3回。",
      reason: "外での基本。",
      testType: "trial",
      measure: { overSteps: 20, reps: 3, successes: 3 },
      requires: ["loose-leash:L2"],
    },
    {
      level: 5,
      condition: "人が通る歩道で歩く。",
      steps: [
        "ときどき人が通る歩道を歩く。",
        "50歩のあいだ、リードが張った回数を数える。",
        "張った回数が2回以下ならOK。",
      ],
      criterion: "50歩のうち、リードが張る回数が2回以下。",
      reason: "軽い刺激があっても引っ張らない。",
      testType: "tally",
      measure: { maxFaults: 2, overSteps: 50, successes: 2 },
      requires: ["loose-leash:L4"],
    },
    {
      level: 6,
      condition: "公園で歩く。",
      steps: [
        "人や犬がいる公園を歩く。",
        "1分間、リードが張った回数を数える。",
        "張った回数が3回以下ならOK。",
      ],
      criterion: "1分間の歩行で、張る回数が3回以下。",
      reason: "どこでも引っ張らない散歩（毎日が楽になる）。",
      testType: "tally",
      measure: { holdSeconds: 60, maxFaults: 3 },
      requires: ["loose-leash:L5"],
    },
  ],

  heel: [
    {
      level: 1,
      condition: "左側につけて少し歩く。",
      steps: [
        "おやつを左手に持ち、犬を自分の左側、ひざのあたりにつける。",
        "おやつで誘導しながら、横位置を保って2歩進む。",
        "横についたまま歩けたら「Yes」→おやつ。",
      ],
      criterion: "横位置を保って2歩、5回。",
      reason: "脚側（左にぴったり）の定位置を覚える。",
      testType: "trial",
      measure: { overSteps: 2, reps: 5, successes: 5 },
      requires: ["loose-leash:L2", "touch:L3", "watch-me:L2"],
    },
    {
      level: 2,
      condition: "「つけ」で横につかせる。",
      steps: [
        "「つけ」と言って歩き出す。",
        "横位置を保って5歩進む。",
        "保てたら「Yes」→おやつ。",
      ],
      criterion: "横位置を維持して5歩、5回続けて。",
      reason: "言葉で横につける。",
      testType: "trial",
      measure: { overSteps: 5, successes: 5, consecutive: true },
      requires: ["heel:L1"],
    },
    {
      level: 3,
      condition: "止まったら自動で座らせる。",
      steps: [
        "「つけ」で歩く。",
        "立ち止まる。",
        "止まったとき、言わなくても自動で座れたら「Yes」→おやつ。",
      ],
      criterion: "停止時に自動で座る、10回中8回。",
      reason: "脚側＋止まったら座る、のマナー。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["heel:L2", "sit:L4"],
    },
    {
      level: 4,
      condition: "方向転換しても横につかせる。",
      steps: [
        "「つけ」で歩きながら、左右やUターンで向きを変える。",
        "向きが変わっても横位置を保てたら「Yes」→おやつ。",
      ],
      criterion: "各転換で横位置を維持、各10回中8回。",
      reason: "方向が変わってもついてくる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["heel:L2"],
    },
    {
      level: 5,
      condition: "軽い誘惑がある中でヒール。",
      steps: [
        "少し気が散る物がある場所で「つけ」。",
        "横位置・リード張りなしで10歩歩く。",
        "保てたら「Yes」→おやつ。",
      ],
      criterion: "横位置・張り0で10歩、3回。",
      reason: "刺激があっても正確に歩ける。",
      testType: "trial",
      measure: { overSteps: 10, reps: 3, successes: 3 },
      requires: ["heel:L3"],
    },
    {
      level: 6,
      condition: "人や犬がいる中でヒール。",
      steps: [
        "人や犬がいる場所で「つけ」。",
        "横位置を保って20歩、止まったら自動で座る。",
        "できたら「Yes」→おやつ。",
      ],
      criterion: "20歩横位置を維持できる、2回。",
      reason: "雑踏やイベントでも完全に制御して歩ける（上級）。",
      testType: "tally",
      measure: { overSteps: 20, reps: 2, successes: 2 },
      requires: ["heel:L5"],
    },
  ],

  // ───────── 協調ケア ─────────
  "chin-rest": [
    {
      level: 1,
      condition: "手のひらにあごを乗せさせる。",
      steps: [
        "手のひらを上に向け、犬の口の下に出す。",
        "鼻を近づけてきたら「Yes」→ご褒美。あごが手に乗ったら、その瞬間に「Yes」→ご褒美。",
        "おやつは手に握らず、乗った後に別の手から出す。",
      ],
      criterion: "あごが手のひらに乗る、5回続けて。",
      reason: "犬が自分からケアを受ける協調ケアの土台。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1", "touch:L1"],
    },
    {
      level: 2,
      condition: "「あご」と言って乗せさせる。",
      steps: [
        "あごを乗せる動きが出たら、乗った瞬間に「あご」と言ってから「Yes」→ご褒美。",
        "安定したら「あご」と言ってから手を出し、乗ったら「Yes」。",
      ],
      criterion: "言葉1回であごを乗せる、10回中8回。",
      reason: "言葉の合図であご乗せを始められる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["chin-rest:L1"],
    },
    {
      level: 3,
      condition: "あごを乗せたまま5秒保つ。",
      steps: [
        "「あご」で乗せたら、1秒・3秒・5秒と保つ時間をのばす。",
        "保てたら「Yes」→ご褒美。あごを離したら無理強いせず中断する。",
      ],
      criterion: "あごを乗せたまま5秒静止、3回成功。",
      reason: "点眼・耳掃除など“数秒の処置”を受けられる長さにする。",
      testType: "duration",
      measure: { holdSeconds: 5, reps: 3 },
      requires: ["chin-rest:L2"],
    },
    {
      level: 4,
      condition: "あごを乗せたまま、顔まわりへ手を近づけても保つ。",
      steps: [
        "「あご」で乗せたまま、もう一方の手を目・耳・口元へゆっくり近づける。",
        "嫌がる手前で止め、受け入れて保てたら「Yes」→ご褒美。",
        "近づける→軽く触れる、と少しずつ接触を増やす。",
      ],
      criterion: "顔まわりへの接触を受け入れてあごを保つ、10回中8回。",
      reason: "実際のケア（点眼・投薬・耳/目のチェック）を嫌がらず受けられる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["chin-rest:L3"],
    },
  ],

  "paw-target": [
    {
      level: 1,
      condition: "手のひらに前足を乗せさせる。",
      steps: [
        "手のひらを足の下に添える。犬が足を乗せたら「Yes」→ご褒美。最初は一瞬でよい。",
        "口で取ろうとする時は反応せず、足が動いた時だけ「Yes」。",
      ],
      criterion: "前足が手のひらに乗る、5回続けて。",
      reason: "爪切り・足ふきを受け入れる協調ケアの土台。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1", "touch:L1"],
    },
    {
      level: 2,
      condition: "「あんよ」と言って乗せさせる。",
      steps: [
        "乗せる動きが出たら「あんよ」と言ってから手を出す。",
        "乗ったら「Yes」→ご褒美。",
      ],
      criterion: "言葉1回で前足を乗せる、10回中8回。",
      reason: "言葉の合図で足を出させられる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["paw-target:L1"],
    },
    {
      level: 3,
      condition: "乗せた足を3秒保持させる。",
      steps: [
        "「あんよ」で乗せた足を軽く支え、1秒→3秒と保つ。",
        "引っ込めようとしたら握らず、保てた時だけ「Yes」→ご褒美。",
      ],
      criterion: "前足を乗せたまま3秒静止、3回成功。",
      reason: "爪を1本切る時間だけ足を保持できる。",
      testType: "duration",
      measure: { holdSeconds: 3, reps: 3 },
      requires: ["paw-target:L2"],
    },
    {
      level: 4,
      condition: "肉球・爪に触れても足を保持させる。",
      steps: [
        "足を保持したまま、肉球を1本ずつ触る→爪やすり/爪切りを“当てるだけ”。",
        "受け入れて保てたら「Yes」→ご褒美。1日1〜2本でよい。",
      ],
      criterion: "肉球・爪への接触を受け入れて保持、10回中8回。",
      reason: "実際に爪切り・足ふきを嫌がらず受けられる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["paw-target:L3"],
    },
  ],

  // ───────── 生活スキル（追加） ─────────
  give: [
    {
      level: 1,
      condition: "交換でくわえた物を手に渡させる。",
      steps: [
        "犬がおもちゃをくわえている状態で、手のひらを口の下に出し「ちょうだい」。",
        "もう一方の手でおやつを鼻先に出す→物を放して手に乗ったら「Yes」→ご褒美。",
        "渡したらすぐ物を返す（取り上げられない＝安心）。",
      ],
      criterion: "交換でおもちゃを手のひらに渡す、5回続けて。",
      reason: "物を気持ちよく手放す土台。守り（リソースガード）を防ぐ。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1", "drop-it:L1"],
    },
    {
      level: 2,
      condition: "「ちょうだい」だけで手に渡させる。",
      steps: [
        "おやつのにおいを見せず「ちょうだい」と言う。",
        "手のひらに渡せたら「Yes」→ご褒美。",
      ],
      criterion: "言葉1回で手に渡す、10回中8回。",
      reason: "おやつで釣らなくても手に渡せる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["give:L1"],
    },
    {
      level: 3,
      condition: "価値の高い物でも手に渡させる。",
      steps: [
        "ガムや拾った物など、手放しにくい物で「ちょうだい」。",
        "渡せたら「Yes」→より良いおやつと交換し、できれば返す。",
      ],
      criterion: "価値の高い物を手に渡す、10回中8回。",
      reason: "危険物・拾い食いを安全に回収できる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["give:L2"],
    },
  ],

  fetch: [
    {
      level: 1,
      condition: "転がした物をくわえさせる。",
      steps: [
        "好きなおもちゃを30cm先に転がす。",
        "追ってくわえたら「Yes」→ご褒美。",
      ],
      criterion: "転がした物をくわえる、5回続けて。",
      reason: "持来（もってきて）の第一歩。物を追ってくわえる。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1", "give:L1"],
    },
    {
      level: 2,
      condition: "くわえて手元へ戻らせる。",
      steps: [
        "くわえたら名前を呼ぶ／自分が後ずさりして、来るのを誘う。",
        "こちらへ戻ってきたら「Yes」→ご褒美。",
      ],
      criterion: "物をくわえて手元へ戻る、10回中7回。",
      reason: "投げた物を持ち帰る往路ができる。",
      testType: "trial",
      measure: { trials: 10, successes: 7 },
      requires: ["fetch:L1"],
    },
    {
      level: 3,
      condition: "手に渡して再投球まで（往復の完成）。",
      steps: [
        "戻ってきたら「ちょうだい」で手に渡させる。",
        "渡したらすぐまた投げる（戻る＝もう一度遊べる）。",
      ],
      criterion: "投げる→くわえる→手に渡す、の往復を10回中7回。",
      reason: "もってきて遊びが一連の流れとして成立する。",
      testType: "trial",
      measure: { trials: 10, successes: 7 },
      requires: ["fetch:L2", "give:L2"],
    },
    {
      level: 4,
      condition: "距離5mでも往復させる。",
      steps: [
        "投げる距離を3m→5mとのばす。",
        "5m先から往復して手に渡せたら「Yes」。途中で遊び始めたら一度終了する。",
      ],
      criterion: "5m先からの往復を10回中7回。",
      reason: "運動量を確保できる実用的なもってきてになる。",
      testType: "trial",
      measure: { trials: 10, successes: 7 },
      requires: ["fetch:L3"],
    },
  ],

  quiet: [
    {
      level: 1,
      condition: "吠えを一瞬やめさせる。",
      steps: [
        "犬が吠えている時、おやつを鼻先に近づける。",
        "においを嗅ぐために吠えが一瞬止まった瞬間に「Yes」→ご褒美。",
      ],
      criterion: "吠えが止まって静かになる瞬間を作れる、5回。",
      reason: "“静かになる瞬間”を捉えて強化する出発点。",
      testType: "trial",
      measure: { successes: 5 },
      requires: ["marker:L1"],
    },
    {
      level: 2,
      condition: "「静かに」で吠えをやめさせる。",
      steps: [
        "静かになった瞬間に「静かに」と言ってから「Yes」→ご褒美。",
        "安定したら吠えている時に「静かに」と言い、止まったら「Yes」。",
      ],
      criterion: "「静かに」で吠えが止まる、10回中8回。",
      reason: "言葉の合図で吠えを止められる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["quiet:L1"],
    },
    {
      level: 3,
      condition: "静かな状態を10秒キープさせる。",
      steps: [
        "「静かに」で止まったら、すぐにご褒美を出さず数秒待つ。",
        "3秒→10秒と静かでいられたら「Yes」→ご褒美。",
      ],
      criterion: "「静かに」の後、10秒静かでいられる、3回成功。",
      reason: "一瞬止むだけでなく、静かな状態を保てるようにする。",
      testType: "duration",
      measure: { holdSeconds: 10, reps: 3 },
      requires: ["quiet:L2"],
    },
    {
      level: 4,
      condition: "吠えの引き金があっても静かにさせる。",
      steps: [
        "インターホン・来客・窓の外の人など、吠える引き金を1つ用意する。",
        "引き金の直後に「静かに」。静かにできたら「Yes」→ご褒美。引き金ごとに練習する。",
      ],
      criterion: "実際の引き金がある場面で「静かに」が効く、10回中8回。",
      reason: "本当に困る“チャイムや来客の吠え”に対応できる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["quiet:L3"],
    },
  ],

  "crate-out": [
    {
      level: 1,
      condition: "ドアを少し開けても飛び出さない。",
      steps: [
        "クレートに入った犬の前で、ドアをほんの少し開ける。",
        "出ようとしたら無言で閉める。出ずに待てたら「Yes」→中でご褒美。",
      ],
      criterion: "ドアを少し開けても出ずに待つ、5回続けて。",
      reason: "出口が開いても飛び出さない自制の土台。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["crate:L1", "release:L1"],
    },
    {
      level: 2,
      condition: "全開でも待ち、解除語で出る。",
      steps: [
        "開ける幅を少しずつ広げ、全開でも待てるようにする。",
        "待てたら解除語（OK/ブレイク）で出るよう促し、出たらご褒美。",
      ],
      criterion: "全開で待ち、解除語で出る、10回中8回。",
      reason: "出る合図を解除語に統一し、勝手な飛び出しをなくす。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["crate-out:L1"],
    },
    {
      level: 3,
      condition: "車のドア・キャリーでも待って解除で出る。",
      steps: [
        "車のドアやキャリーの扉でも同じように、開けて待たせる。",
        "待てたら解除語で出す。場所を変えて試す。",
      ],
      criterion: "別の出口でも待って解除で出る、各10回中8回。",
      reason: "車・キャリーからの飛び出し事故を防ぐ。",
      testType: "trial",
      measure: { trials: 10, successes: 8, places: 2 },
      requires: ["crate-out:L2"],
    },
  ],

  "door-wait": [
    {
      level: 1,
      condition: "ドアノブに触れても動かない。",
      steps: [
        "玄関の前で犬を座らせ「待って」。ドアノブに手をかける。",
        "動かなければ「Yes」→ご褒美。動いたらノブから手を離してやり直す。",
      ],
      criterion: "ノブに触れても動かずにいる、5回続けて。",
      reason: "玄関で勝手に動かない出発点。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["wait:L1", "release:L1"],
    },
    {
      level: 2,
      condition: "ドアを開けても待ち、解除語で出る。",
      steps: [
        "ノブを回す→数cm開ける→大きく開ける、と段階を進める。",
        "動いたらドアを閉め一段戻る。全開でも待てたら解除語で外へ出す。",
      ],
      criterion: "ドアを全開にしても待ち、解除語で出る、10回中8回。",
      reason: "玄関からの飛び出しを防ぎ、出る合図を解除語に統一する。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["door-wait:L1"],
    },
    {
      level: 3,
      condition: "別の出口（共用扉・門など）でも待つ。",
      steps: [
        "マンション共用扉・門・公園のゲートなど、別の出口でも同じ手順で待たせる。",
        "待てたら解除語で進ませる。",
      ],
      criterion: "別の出口でも待って解除で進む、各10回中8回。",
      reason: "どの出口でも飛び出さない生活習慣にする。",
      testType: "trial",
      measure: { trials: 10, successes: 8, places: 2 },
      requires: ["door-wait:L2"],
    },
  ],

  car: [
    {
      level: 1,
      condition: "自分から車に乗る。",
      steps: [
        "エンジンを切った車で、ドアを開けおやつを車内に置く。",
        "自分から乗ったら「Yes」→車内でご褒美。",
      ],
      criterion: "自分から車に乗り込む、5回。",
      reason: "車＝怖くない場所、という第一歩。",
      testType: "trial",
      measure: { successes: 5 },
      requires: ["release:L1"],
    },
    {
      level: 2,
      condition: "「乗って」で乗る。",
      steps: [
        "乗る動きが出たら「乗って」と言ってから誘導する。",
        "乗ったら「Yes」→車内で落ち着けるよう数粒あげる。",
      ],
      criterion: "「乗って」で車に乗る、10回中8回。",
      reason: "言葉の合図で乗せられる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["car:L1"],
    },
    {
      level: 3,
      condition: "降りるとき待って、解除語で降りる。",
      steps: [
        "停車してドアを開けたら「待って」。飛び降りさせない。",
        "待てたら解除語で「降りて」と促す。降りたらご褒美。",
      ],
      criterion: "ドアを開けても待ち、解除語で降りる、10回中8回。",
      reason: "車道側への飛び降り事故を防ぐ。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["car:L2", "wait:L1"],
    },
    {
      level: 4,
      condition: "短いドライブで落ち着いていられる。",
      steps: [
        "クレートかドッグシートベルトで固定し、近所を数分走る。",
        "吠え続け・過剰なよだれ・嘔吐がなく過ごせたらOK。短時間から少しずつのばす。",
      ],
      criterion: "数分のドライブを落ち着いて過ごす、3回成功。",
      reason: "通院・旅行・避難で実際に車移動できる。",
      testType: "trial",
      measure: { trials: 3, successes: 3, consecutive: true },
      requires: ["car:L3"],
    },
  ],

  "go-to-bed": [
    {
      level: 1,
      condition: "ベッドに乗って伏せる。",
      steps: [
        "ベッドのそばで「ベッド」と言い、乗ったら「Yes」→ベッドの上でご褒美。",
        "乗れたら「ふせ」、伏せたら「Yes」→ベッドの上でご褒美（床ではあげない）。",
      ],
      criterion: "ベッドに乗って伏せる、5回。",
      reason: "ベッド＝伏せて落ち着く場所、を結びつける。",
      testType: "trial",
      measure: { successes: 5 },
      requires: ["place:L1", "down:L4", "settle:L1"],
    },
    {
      level: 2,
      condition: "離れた場所から「ベッド」で行って伏せる。",
      steps: [
        "送り出す距離を1m→3mとのばす。",
        "離れた所から「ベッド」で行き、自分で伏せたら「Yes」→ベッドの上でご褒美。",
      ],
      criterion: "3m離れた所から行って伏せる、10回中8回。",
      reason: "離れていてもベッドへ送り出せる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["go-to-bed:L1"],
    },
    {
      level: 3,
      condition: "ベッドで1分伏せて待つ。",
      steps: [
        "「ベッド」で伏せさせたら、すぐ解除せず時間をのばす。",
        "10秒→30秒→1分と伏せて待てたら「Yes」→ご褒美、最後に解除語で終了。",
      ],
      criterion: "ベッドで1分伏せて待つ、3回成功。",
      reason: "来客対応や食事の間、その場で待たせられる長さにする。",
      testType: "duration",
      measure: { holdSeconds: 60, reps: 3 },
      requires: ["go-to-bed:L2"],
    },
    {
      level: 4,
      condition: "来客・チャイムの誘惑があってもベッドで待つ。",
      steps: [
        "インターホンを鳴らす・家族が出入りするなど誘惑を作る。",
        "ベッドから出ずに待てたら「Yes」→ご褒美。出たら静かにベッドへ戻す。",
      ],
      criterion: "誘惑がある場面でもベッドで待機、10回中8回。",
      reason: "本番（来客・宅配・食事中）で実際に役立つ。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["go-to-bed:L3"],
    },
  ],

  gentle: [
    {
      level: 1,
      condition: "握った手がゆるむまで待ち、やさしく受け取らせる。",
      steps: [
        "おやつを拳に握り込む。犬が噛んだり舐めたりしても開けない。",
        "勢いがゆるんで鼻や舌でそっと触れた瞬間に「そっと」と言い、手を開いて食べさせる。",
      ],
      criterion: "歯を当てずにそっと受け取る、5回。",
      reason: "ガツガツ＝もらえない／そっと＝もらえる、を教える出発点。",
      testType: "trial",
      measure: { successes: 5 },
      requires: ["marker:L1"],
    },
    {
      level: 2,
      condition: "「そっと」で歯を当てずに受け取る。",
      steps: [
        "指でつまんだおやつを差し出し「そっと」と言う。",
        "歯を当てずに受け取れたら「Yes」。歯が当たったら手を引いてやり直す。",
      ],
      criterion: "「そっと」で歯を当てずに受け取る、10回中8回。",
      reason: "指を噛まれる事故を防ぐ。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["gentle:L1"],
    },
    {
      level: 3,
      condition: "興奮しやすい場面・価値の高いおやつでもそっと受け取る。",
      steps: [
        "ジャーキーなど大好きなおやつや、遊びで興奮した直後に「そっと」。",
        "落ち着いてやさしく受け取れたら「Yes」→ご褒美。",
      ],
      criterion: "価値の高いおやつ・興奮時でもそっと受け取る、10回中8回。",
      reason: "子ども・高齢者が与える時も安全に受け取れる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["gentle:L2"],
    },
  ],

  // ───────── トリック・芸 ─────────
  shake: [
    {
      level: 1,
      condition: "前足を持ち上げて手に乗せさせる。",
      steps: [
        "犬を座らせ、おやつを握った拳を前足の少し上に出す。",
        "前足で取ろうとして足が上がり、手に乗った瞬間に「Yes」→手を開いてご褒美。",
      ],
      criterion: "前足が手のひらに乗る、5回続けて。",
      reason: "教えやすい最初のトリック。成功体験を作る。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1", "sit:L4"],
    },
    {
      level: 2,
      condition: "「お手」と言って前足を出させる。",
      steps: [
        "足を上げる動きが安定したら「お手」と言ってから手を出す。",
        "握りおやつを“開いた手のひら”に替え、乗ったら別の手からご褒美。",
      ],
      criterion: "「お手」で前足を乗せる、10回中8回。",
      reason: "言葉の合図でお手ができる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["shake:L1"],
    },
    {
      level: 3,
      condition: "左右どちらの手にも、いろいろな人にも出せる。",
      steps: [
        "右手・左手どちらを出しても「お手」で乗せられるようにする。",
        "家族など別の人が手を出しても乗せられたら「Yes」→ご褒美。",
      ],
      criterion: "左右の手・別の人の手でもお手ができる、各10回中8回。",
      reason: "誰の前でも挨拶として使える。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["shake:L2"],
    },
  ],

  "shake-other": [
    {
      level: 1,
      condition: "お手と反対の前足を手に乗せさせる。",
      steps: [
        "お手を仕上げてから始める。反対側の手を、反対の前足の前に出す。",
        "うっかりお手側の足を出したら反応せず、反対の足が乗った瞬間だけ「Yes」→ご褒美。",
      ],
      criterion: "反対側の前足が手に乗る、5回続けて。",
      reason: "左右の足を区別して出す第一歩。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["shake:L2"],
    },
    {
      level: 2,
      condition: "「おかわり」で反対の足を出させる。",
      steps: [
        "反対の足が出る動きが安定したら「おかわり」と言ってから手を出す。",
        "乗ったら「Yes」→ご褒美。",
      ],
      criterion: "「おかわり」で反対の足を乗せる、10回中8回。",
      reason: "言葉の合図でおかわりができる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["shake-other:L1"],
    },
    {
      level: 3,
      condition: "「お手」「おかわり」を聞き分けて出し分ける。",
      steps: [
        "「お手」「おかわり」をランダムに出す。",
        "号令に合った正しい足を出せたら「Yes」→ご褒美。",
      ],
      criterion: "号令どおりの足を出し分ける、10回中8回。",
      reason: "左右を聞き分け、芸として完成させる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["shake-other:L2"],
    },
  ],

  // ───────── 人気トリック ─────────
  spin: [
    {
      level: 1,
      condition: "手の誘導で、その場で一周回る。",
      steps: [
        "鼻先のおやつを体に沿って円を描くように動かす。",
        "つられて一周回りきった瞬間に「Yes」→ご褒美。",
      ],
      criterion: "手の誘導で一周回る、5回続けて。",
      reason: "教えやすい最初のトリック。成功体験を作る。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1"],
    },
    {
      level: 2,
      condition: "「クルッ」の合図で回る（手は小さく）。",
      steps: [
        "回れるようになったら「クルッ」と言ってから手を回す。",
        "手の動きを少しずつ小さくしていく。",
      ],
      criterion: "言葉＋小さな合図で一周回る、10回中8回。",
      reason: "合図で回せる。手を抜いていく。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["spin:L1"],
    },
  ],
  "roll-over": [
    {
      level: 1,
      condition: "ふせから横向きに倒れる（半回転）。",
      steps: [
        "「ふせ」から鼻先のおやつを肩越しに動かす。",
        "体が横向きに倒れたら「Yes」→ご褒美。",
      ],
      criterion: "誘導で横向きまで倒れる、5回続けて。",
      reason: "一回転の前半をていねいに作る。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1", "down:L4"],
    },
    {
      level: 2,
      condition: "誘導で一回転する。",
      criterion: "おやつ誘導でコロンと一回転、10回中8回。",
      reason: "回転の動きを完成させる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["roll-over:L1"],
    },
    {
      level: 3,
      condition: "「ゴロン」の合図で一回転する。",
      criterion: "言葉＋小さな合図で一回転、10回中8回。",
      reason: "合図だけでできる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["roll-over:L2"],
    },
  ],
  "high-five": [
    {
      level: 1,
      condition: "立てた手のひらに前足を当てる。",
      criterion: "立てた手に前足が当たる、5回続けて。",
      reason: "お手から芸の幅を広げる。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1", "shake:L1"],
    },
    {
      level: 2,
      condition: "「タッチ」の合図で当てる（高さも上げる）。",
      criterion: "「タッチ」で手のひらに当てる、10回中8回。",
      reason: "合図でハイタッチが決まる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["high-five:L1"],
    },
  ],
  wave: [
    {
      level: 1,
      condition: "宙で前足を上下に振る（手に触れずに）。",
      steps: [
        "お手の手を、足が届かない少し手前に出す。",
        "足が宙で上下した瞬間に「Yes」→ご褒美。",
      ],
      criterion: "宙で前足を振る、5回続けて。",
      reason: "“触れずに振る”動きを作る。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1", "shake:L2"],
    },
    {
      level: 2,
      condition: "少し離れて「バイバイ」で振る。",
      criterion: "離れた所から「バイバイ」で振る、10回中8回。",
      reason: "お見送りの芸として使える。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["wave:L1"],
    },
  ],
  bow: [
    {
      level: 1,
      condition: "お尻を上げたまま前半身を下げる。",
      steps: [
        "立たせて鼻先のおやつを前足の間からまっすぐ床へ。",
        "前半身だけ下がり、お尻が上がったままなら「Yes」→ご褒美。",
      ],
      criterion: "お尻を上げたまま前半身を下げる、5回続けて。",
      reason: "ふせと区別したお辞儀の形を作る。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1", "stand:L2"],
    },
    {
      level: 2,
      condition: "「おじぎ」の合図で、2秒キープする。",
      criterion: "合図でお辞儀し2秒キープ、10回中8回。",
      reason: "合図で美しいお辞儀が決まる。",
      testType: "trial",
      measure: { trials: 10, successes: 8, holdSeconds: 2 },
      requires: ["bow:L1"],
    },
  ],
  "play-dead": [
    {
      level: 1,
      condition: "横たわって静止する（誘導）。",
      steps: [
        "「ふせ」から鼻先のおやつを肩越しに動かし横倒しに。",
        "横たわって動きが止まったら「Yes」→ご褒美。",
      ],
      criterion: "横たわって3秒静止する、5回続けて。",
      reason: "“倒れて止まる”形を作る。",
      testType: "trial",
      measure: { successes: 5, consecutive: true, holdSeconds: 3 },
      requires: ["marker:L1", "down:L4"],
    },
    {
      level: 2,
      condition: "「バーン」＋指鉄砲で横たわり静止する。",
      criterion: "合図で横たわり5秒静止、10回中8回。",
      reason: "合図で決まる定番芸に仕上げる。",
      testType: "trial",
      measure: { trials: 10, successes: 8, holdSeconds: 5 },
      requires: ["play-dead:L1"],
    },
  ],
  beg: [
    {
      level: 1,
      condition: "おすわりから両前足を浮かせる。",
      steps: [
        "「おすわり」から鼻先のおやつを頭の真上へ少し持ち上げる。",
        "両前足が浮いたら「Yes」→ご褒美（最初はわずかでOK）。",
      ],
      criterion: "両前足を浮かせてバランスを取る、5回続けて。",
      reason: "腰に無理なく上体を起こす入り口。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1", "sit:L4"],
    },
    {
      level: 2,
      condition: "「ちんちん」で2秒バランスを保つ。",
      criterion: "「ちんちん」で上体を起こし2秒キープ、10回中8回。",
      reason: "可愛い定番芸として完成。",
      testType: "trial",
      measure: { trials: 10, successes: 8, holdSeconds: 2 },
      requires: ["beg:L1"],
    },
  ],
  speak: [
    {
      level: 1,
      condition: "「おはなし」の合図で1回吠える。",
      steps: [
        "吠えやすい状況で吠えた瞬間に「Yes」→ご褒美。",
        "出せるようになったら「おはなし」と言ってから合図する。",
      ],
      criterion: "「おはなし」で1回吠える、10回中8回。",
      reason: "吠えを合図でオンにできる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["marker:L1", "quiet:L1"],
    },
    {
      level: 2,
      condition: "「おはなし」→「静かに」でオン・オフできる。",
      criterion: "合図で吠え、「静かに」で止める、を続けて10回中8回。",
      reason: "吠えのオン・オフを管理できる（安全に芸として成立）。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["speak:L1", "quiet:L1"],
    },
  ],
  "back-up": [
    {
      level: 1,
      condition: "狭い通路でまっすぐ数歩下がる。",
      steps: [
        "壁ぎわの細い通路で犬と向かい合う。",
        "一歩踏み出し、犬が下がった瞬間に「Yes」→ご褒美。",
      ],
      criterion: "まっすぐ2〜3歩下がる、5回続けて。",
      reason: "後退の動きを作る（実用にも）。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1"],
    },
    {
      level: 2,
      condition: "広い場所で「バック」の合図で下がる。",
      criterion: "「バック」でまっすぐ数歩下がる、10回中8回。",
      reason: "合図だけで下がれる。玄関や狭所でも使える。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["back-up:L1"],
    },
  ],
  "find-it": [
    {
      level: 1,
      condition: "見える所のおやつを「さがせ」で探す。",
      steps: [
        "目の前の床におやつを置き「さがせ」で食べさせる。",
        "少し離れた見える所に置き、探させる。",
      ],
      criterion: "「さがせ」で置いたおやつを探して見つける、5回続けて。",
      reason: "“探す”という遊びの土台を作る。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1"],
    },
    {
      level: 2,
      condition: "隠した物を嗅覚で探し当てる。",
      steps: [
        "布やコップの下など見えない所に隠す。",
        "部屋に複数・別の部屋など難易度を上げる。",
      ],
      criterion: "見えない所に隠した物を鼻で見つける、10回中8回。",
      reason: "嗅覚をしっかり使う知育に。退屈・破壊対策にも。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["find-it:L1"],
    },
  ],

  // ───────── 協調ケア ─────────
  "side-lying": [
    {
      level: 1,
      condition: "横向きに寝そべる（誘導）。",
      steps: [
        "「ふせ」から鼻先のおやつを肩越しに動かし、体を横向きに倒す。",
        "横向きに寝たら「Yes」→ご褒美。",
      ],
      criterion: "横向きに寝て3秒静止する、5回続けて。",
      reason: "横向きの保定姿勢を作る（診察・お手入れの土台）。",
      testType: "trial",
      measure: { successes: 5, consecutive: true, holdSeconds: 3 },
      requires: ["marker:L1", "down:L4"],
    },
    {
      level: 2,
      condition: "「ヨコ」の合図で寝て、力を抜いて待つ。",
      criterion: "合図で横になり10秒、力を抜いて静止、10回中8回。",
      reason: "合図で安定して横向き保定ができる。",
      testType: "trial",
      measure: { trials: 10, successes: 8, holdSeconds: 10 },
      requires: ["side-lying:L1"],
    },
    {
      level: 3,
      condition: "横になったまま、足・お腹・耳を触らせる。",
      criterion: "横向きのまま各所を触られても動かない、10回中8回。",
      reason: "肛門腺・お腹・足のお手入れを暴れず受けられる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["side-lying:L2"],
    },
  ],
  station: [
    {
      level: 1,
      condition: "低い台に四肢で乗る。",
      steps: [
        "低くて安定した台を用意し、前足が乗ったら「Yes」→ご褒美。",
        "四肢が乗ったらたっぷり強化する。",
      ],
      criterion: "台に四肢で乗る、5回続けて。",
      reason: "“台＝良い場所”を作る。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1", "touch:L1"],
    },
    {
      level: 2,
      condition: "「のって」で乗り、その上で5秒待つ。",
      criterion: "合図で乗って5秒待つ、10回中8回。",
      reason: "体重測定・トリミング台で待てる。",
      testType: "trial",
      measure: { trials: 10, successes: 8, holdSeconds: 5 },
      requires: ["station:L1"],
    },
    {
      level: 3,
      condition: "いろいろな台で乗って待ち、乗ったまま体を触らせる。",
      criterion: "別の台でも乗って待ち、触られても降りない、10回中8回。",
      reason: "実際の体重計・トリミング台で使える。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["station:L2"],
    },
  ],
  muzzle: [
    {
      level: 1,
      condition: "口輪に自分から鼻を入れる。",
      steps: [
        "バスケット型口輪の中におやつを塗り、差し出す。",
        "自分から鼻を入れて舐めたら「Yes」→ご褒美。押し付けない。",
      ],
      criterion: "自分から鼻を口輪に入れる、5回続けて。",
      reason: "口輪＝良いことの合図、の第一歩。",
      testType: "trial",
      measure: { successes: 5, consecutive: true },
      requires: ["marker:L1", "touch:L1"],
    },
    {
      level: 2,
      condition: "鼻を入れて5秒キープ＋ストラップに触れさせる。",
      criterion: "鼻を入れて5秒、首後ろのストラップに触れても平気、10回中8回。",
      reason: "装着の一歩手前まで受け入れる。",
      testType: "trial",
      measure: { trials: 10, successes: 8, holdSeconds: 5 },
      requires: ["muzzle:L1"],
    },
    {
      level: 3,
      condition: "装着して短い時間を落ち着いて過ごす。",
      criterion: "口輪を留めて1〜2分、落ち着いて過ごせる（散歩・診察を想定）。",
      reason: "通院や処置で実際に使える。",
      testType: "duration",
      measure: { holdSeconds: 60, reps: 1 },
      requires: ["muzzle:L2"],
    },
  ],
};

// ケア・装着系のレベル（careTasks.ts の id に対応）
export const careLevels: Record<string, CommandLevel[]> = {
  collar: [
    {
      level: 1,
      condition: "首輪に良い印象をつける。",
      steps: [
        "首輪を手に持って、犬に見せる・においを嗅がせる。",
        "近づいたら「Yes」→おやつ。道具＝良いこと、にする。",
      ],
      criterion: "首輪に自分から近づく、5回。",
      reason: "道具を「怖くない物」にする。",
      testType: "trial",
      measure: { successes: 5 },
    },
    {
      level: 2,
      condition: "首に少しあてて慣らす。",
      steps: [
        "首輪を、首に1秒だけそっとあてる（まだ留めない）。",
        "嫌がらなければ「Yes」→おやつ。",
        "少しずつ、あてる時間をのばす。",
      ],
      criterion: "嫌がらず受け入れる、10回中8回。",
      reason: "装着の前の段階。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["collar:L1"],
    },
    {
      level: 3,
      condition: "短時間、装着する。",
      steps: [
        "首輪を留めて装着する。",
        "掻いたり気にしたりする前に、おもちゃやおやつで気をそらす。",
        "10秒、気にせず過ごせたら「Yes」→おやつ。",
      ],
      criterion: "掻いたり暴れたりしない、10回中8回。",
      reason: "短い装着に慣れる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["collar:L2"],
    },
    {
      level: 4,
      condition: "つけたまま生活させる。",
      steps: [
        "首輪をつけたまま、食事や遊びをさせる。",
        "掻く前に、活動に集中させる。",
        "30分、気にせず過ごせればOK。",
      ],
      criterion: "30分間、気にせず過ごせる。",
      reason: "装着が日常になる。",
      testType: "duration",
      measure: { holdSeconds: 600 },
      requires: ["collar:L3"],
    },
    {
      level: 5,
      condition: "24時間つけて生活させる。",
      steps: [
        "首輪を24時間つけて生活させる。",
        "外そうとする・掻き続ける様子が1日を通して見られなければOK。",
      ],
      criterion: "外そうとする・掻き続ける行動が1日を通して見られない。",
      reason: "迷子札を常時つけられる（安全）。",
      testType: "tally",
      measure: { streakDays: 1 },
      requires: ["collar:L4"],
    },
  ],

  leash: [
    {
      level: 1,
      condition: "リードに良い印象をつける。",
      steps: [
        "リードを手に持って見せる・においを嗅がせる。",
        "近づいたら「Yes」→おやつ。",
      ],
      criterion: "リードに自分から近づく、5回。",
      reason: "道具を「怖くない物」にする。",
      testType: "trial",
      measure: { successes: 5 },
    },
    {
      level: 2,
      condition: "付けて床に垂らして慣らす。",
      steps: [
        "首輪にリードを付けて、床に垂らす（まだ持たない）。",
        "リードを引きずったまま動けたら「Yes」→おやつ。",
      ],
      criterion: "気にせず動ける、10回中8回。",
      reason: "付いている違和感を取る。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["collar:L3", "leash:L1"],
    },
    {
      level: 3,
      condition: "室内で一緒に歩く。",
      steps: [
        "リードを軽く持って、室内を一緒に歩く（引っ張らない）。",
        "パニックにならず数歩歩けたらOK。",
      ],
      criterion: "パニックにならず数歩歩ける、5回。",
      reason: "テンションなしで歩く感覚をつかむ。",
      testType: "trial",
      measure: { successes: 5 },
      requires: ["leash:L2"],
    },
    {
      level: 4,
      condition: "リードを噛まずに歩ける。",
      steps: [
        "リードをたるませて持ち、歩く。噛もうとしたら立ち止まって動きを止める（噛む＝つまらない、にする）。",
        "口を離して落ち着いたら歩き再開（歩く＝楽しい、にする）。引っ張り返さない・声を上げない。",
        "噛みたがる時は、噛んでよいおもちゃに持ち替えさせて発散させる。",
      ],
      criterion: "リードを噛まずに室内を1分歩ける、3回。",
      reason: "リードを“おもちゃ”にせず、歩く道具として受け入れる。",
      testType: "trial",
      measure: { successes: 3 },
      requires: ["leash:L3"],
    },
    {
      level: 5,
      condition: "庭・玄関先で歩く。",
      steps: [
        "庭や玄関先で、リードを付けて短く歩く。",
        "落ち着いて・噛まずに歩ければOK。",
      ],
      criterion: "落ち着いて歩ける、3回。",
      reason: "屋外でのリード歩行の前提。",
      testType: "trial",
      measure: { successes: 3 },
      requires: ["leash:L4"],
    },
  ],

  harness: [
    {
      level: 1,
      condition: "ハーネスに良い印象をつける。",
      steps: [
        "ハーネスを見せて、においを嗅がせる。",
        "近づいたら「Yes」→おやつ。",
      ],
      criterion: "自分から近づく、5回。",
      reason: "道具を「怖くない物」にする。",
      testType: "trial",
      measure: { successes: 5 },
    },
    {
      level: 2,
      condition: "自分から鼻を輪に通す（噛ませない）。",
      steps: [
        "頭を通す輪の“向こう側”におやつを持ち、犬が自分から鼻を通したらおやつ。",
        "ヒラヒラ振らず静かに差し出す。口で噛もうとしたら、鼻を通す方へ誘導しおやつで口を埋める。",
        "「輪に鼻を通す＝良いこと」を作る。引っ張り合い（タグ）にしない。",
      ],
      criterion: "自分から鼻を輪に通す、10回中8回。",
      reason: "装着の核心。ハーネスをおもちゃにせず、自分から通す形を作る。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["harness:L1"],
    },
    {
      level: 3,
      condition: "1動作ずつ最後まで装着する。",
      steps: [
        "鼻を通したら、脚を入れる・留め具を留める動作を1つずつ。",
        "1動作ごとに「Yes」→おやつ。嫌がったら手前で止める。",
      ],
      criterion: "嫌がらず最後まで装着できる、10回中8回。",
      reason: "装着を一通り受け入れる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["harness:L2"],
    },
    {
      level: 4,
      condition: "つけて過ごさせる。",
      steps: [
        "ハーネスを装着して10分過ごす。",
        "気にせず過ごせればOK。",
      ],
      criterion: "10分間、気にせず過ごせる。",
      reason: "胴輪での歩行の前提。",
      testType: "duration",
      measure: { holdSeconds: 600 },
      requires: ["harness:L3"],
    },
  ],

  "body-handling": [
    {
      level: 1,
      condition: "肩・背中を触らせる。",
      steps: [
        "犬がリラックスしているとき、肩や背中をやさしく撫でる。",
        "逃げずに受け入れたら「Yes」→おやつ。",
      ],
      criterion: "逃げず受け入れる、10回中8回。",
      reason: "触られ慣れの土台。すべてのケアの前提。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["marker:L1"],
    },
    {
      level: 2,
      condition: "全身を触らせる。",
      steps: [
        "脇腹・胸・しっぽの付け根まで、全身をやさしく撫でる。",
        "力を抜いて受けていたら「Yes」→おやつ。嫌がる場所は、短く・やさしく。",
      ],
      criterion: "リラックスして受ける、10回中8回。",
      reason: "全身を触られても平気にする。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["body-handling:L1"],
    },
    {
      level: 3,
      condition: "正しい抱っこで抱え上げさせる。",
      steps: [
        "片手で胸（前足の後ろ）を、もう片方の腕でお尻・後ろ足を下から支える。",
        "体を自分に密着させ、ブラブラさせずに“数秒だけ”抱え上げる。",
        "暴れずに受け入れたら「Yes」→おやつ→そっと下ろす。前足だけで吊り上げない。",
      ],
      criterion: "正しい抱っこで暴れず受け入れる、10回中8回。",
      reason: "通院・移動・緊急時に、犬が安心できる抱っこをする。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["body-handling:L2"],
    },
    {
      level: 4,
      condition: "膝の上で仰向けに安心できる。",
      steps: [
        "床に座り、犬を膝の上で横向きに抱える→少し傾ける、と段階的に。",
        "背中を支えて短時間あお向けにする。リラックスできた瞬間に「Yes」→おやつ。",
        "嫌がったら起こしてやり直す（押さえつけない）。保てる時間を少しずつ延ばす。",
      ],
      criterion: "仰向けで力を抜いて10秒落ち着ける、5回。",
      reason: "お腹のブラッシングや、上からの歯みがき・点眼を安心して受けられる土台になる。",
      testType: "duration",
      measure: { holdSeconds: 10, reps: 5 },
      requires: ["body-handling:L3"],
    },
  ],

  paws: [
    {
      level: 1,
      condition: "足先を触らせる。",
      steps: [
        "犬が伏せている／落ち着いている時に、横から足の“甲”にそっと手を添える。",
        "1秒触れて引っ込めなければ「Yes」→おやつ。引っ込める前に手を離すのがコツ。",
        "前足だけでなく後ろ足も同じように。",
      ],
      criterion: "引っ込めず受け入れる、10回中8回。",
      reason: "爪切り・足拭きの前提。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["body-handling:L1"],
    },
    {
      level: 2,
      condition: "足を持たせる。",
      steps: [
        "各足を、やさしく持って5秒保つ。",
        "引っ込めなければ「Yes」→おやつ。4本とも行う。",
      ],
      criterion: "各足で引っ込めない、各10回中8回。",
      reason: "足を扱えるようにする。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["paws:L1"],
    },
    {
      level: 3,
      condition: "肉球を広げさせる。",
      steps: [
        "足を持ち、親指で肉球を軽く押し広げる。",
        "受け入れたら「Yes」→おやつ。指の間も少しずつ触れる（汚れ・でき物のチェックになる）。",
      ],
      criterion: "受け入れる、10回中8回。",
      reason: "肉球・指の間のチェック。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["paws:L2"],
    },
  ],

  mouth: [
    {
      level: 1,
      condition: "口先を触らせる。",
      steps: [
        "犬の鼻先（マズル）の上に、手をそっとのせる。口は握らない。",
        "1秒のせて嫌がらなければ「Yes」→おやつ。少しずつ時間を延ばす。",
      ],
      criterion: "受け入れる、10回中8回。",
      reason: "歯みがき・口のチェックの前提。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["body-handling:L1"],
    },
    {
      level: 2,
      condition: "歯を見せさせる。",
      steps: [
        "上唇を片側だけ“ペロッ”とめくり、外側の歯を一瞬見せる。",
        "受け入れたら「Yes」→おやつ。反対側・奥歯と、見せる範囲を少しずつ広げる。",
      ],
      criterion: "受け入れる、10回中8回。",
      reason: "歯のチェック。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["mouth:L1"],
    },
    {
      level: 3,
      condition: "歯ぐきを触らせる。",
      steps: [
        "唇をめくり、歯ぐき（歯と歯肉の境目）に指で軽く触れる。歯みがきで磨く場所。",
        "受け入れたら「Yes」→おやつ。触れる時間と範囲を少しずつ広げる。",
      ],
      criterion: "受け入れる、10回中8回。",
      reason: "歯みがきの直前の段階。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["mouth:L2"],
    },
  ],

  ears: [
    {
      level: 1,
      condition: "耳の付け根を触らせる。",
      steps: [
        "耳の付け根を、軽くマッサージするようにそっと触れる。",
        "受け入れたら「Yes」→おやつ。左右とも。嫌がる子は外側を撫でるところから。",
      ],
      criterion: "受け入れる、10回中8回。",
      reason: "耳掃除・外耳炎チェックの前提。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["body-handling:L1"],
    },
    {
      level: 2,
      condition: "耳の中を見させる。",
      steps: [
        "耳たぶを持って“めくり”、中を1秒見る。",
        "受け入れたら「Yes」→おやつ。見る時間を少しずつ延ばす。赤み・汚れ・においもチェック。",
      ],
      criterion: "受け入れる、10回中8回。",
      reason: "耳の中の確認（外耳炎の早期発見）。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["ears:L1"],
    },
  ],

  brushing: [
    {
      level: 1,
      condition: "ブラシに良い印象をつける。",
      steps: [
        "ブラシを見せて、においを嗅がせる。",
        "近づいたら「Yes」→おやつ。",
      ],
      criterion: "自分から近づく、5回。",
      reason: "道具を「怖くない物」にする。",
      testType: "trial",
      measure: { successes: 5 },
    },
    {
      level: 2,
      condition: "1ストロークだけ慣らす。",
      steps: [
        "ブラシで体を、1ストロークだけする。",
        "逃げなければ「Yes」→おやつ。",
      ],
      criterion: "逃げず受ける、10回中8回。",
      reason: "ブラシの感触に慣れる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["body-handling:L2", "brushing:L1"],
    },
    {
      level: 3,
      condition: "続けてブラッシングする。",
      steps: [
        "数ストローク、続けてブラッシングする。",
        "逃げず受けたら「Yes」→おやつ。",
      ],
      criterion: "逃げず受ける、10回中8回。",
      reason: "続けて受けられる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["brushing:L2"],
    },
    {
      level: 4,
      condition: "お腹・脇・内股までブラッシングする。",
      steps: [
        "膝の上で仰向けに抱え、毛玉ができやすいお腹・脇・内股をやさしくとかす。",
        "嫌がりやすい場所なので、1ストロークずつ・短く。受けたら「Yes」→おやつ。",
      ],
      criterion: "お腹・脇を逃げず受ける、10回中8回。",
      reason: "背中だけでなく、毛玉になりやすい場所までケアできる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["brushing:L3", "body-handling:L4"],
    },
    {
      level: 5,
      condition: "全身をブラッシングする。",
      steps: [
        "背中からお腹まで、全身を続けてブラッシングする。",
        "落ち着いて1分間受けられればOK。",
      ],
      criterion: "落ち着いて1分間受ける、3回。",
      reason: "日常の毛のケアが完成。",
      testType: "duration",
      measure: { holdSeconds: 60, reps: 3 },
      requires: ["brushing:L4"],
    },
  ],

  teeth: [
    {
      level: 1,
      condition: "歯みがき道具に良い印象をつける。",
      steps: [
        "犬用の歯みがきペーストを、歯ブラシか指サックにつける。",
        "犬に舐めさせる。自分から舐めたら「Yes」→おやつ。",
      ],
      criterion: "自分から舐める、5回。",
      reason: "歯みがき道具を「おいしい・良い物」にする。",
      testType: "trial",
      measure: { successes: 5 },
      requires: ["mouth:L2"],
    },
    {
      level: 2,
      condition: "前歯を少し磨く。",
      steps: [
        "上唇をめくり、ペーストをつけた歯ブラシ／指サックで前歯を1〜2本、軽くこする（数秒）。",
        "受け入れたら「Yes」→おやつ。歯ブラシを噛む子は、ガーゼを指に巻いて磨くと受け入れやすい。",
      ],
      criterion: "受け入れる、10回中8回。",
      reason: "ブラシの感触に慣れる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["teeth:L1"],
    },
    {
      level: 3,
      condition: "片側を磨く。",
      steps: [
        "片側の歯（前歯→犬歯→奥歯）の外側を、歯と歯ぐきの境目を意識して数秒磨く。",
        "受け入れたら「Yes」→おやつ。内側は舌が掃除するので外側だけでよい。",
      ],
      criterion: "受け入れる、10回中8回。",
      reason: "磨く範囲を広げる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["teeth:L2"],
    },
    {
      level: 4,
      condition: "全体を磨く。",
      steps: [
        "全体を続けて磨く。",
        "落ち着いて30秒磨ければOK。",
      ],
      criterion: "落ち着いて30秒磨ける、10回中8回。",
      reason: "歯周病予防の習慣が完成。",
      testType: "duration",
      measure: { holdSeconds: 30, trials: 10, successes: 8 },
      requires: ["teeth:L3"],
    },
  ],

  nails: [
    {
      level: 1,
      condition: "爪切りに良い印象をつける。",
      steps: [
        "爪切りを見せて、においを嗅がせる。",
        "近づいたら「Yes」→おやつ。",
      ],
      criterion: "自分から近づく、5回。",
      reason: "爪切りを「怖くない物」にする。",
      testType: "trial",
      measure: { successes: 5 },
    },
    {
      level: 2,
      condition: "切る姿勢でリラックスさせる。",
      steps: [
        "リックマット（床や壁に塗ったペースト）をなめさせながら、足をやさしく持つ姿勢にする。",
        "足を“後ろ向き”に軽く曲げて持つと、犬から刃が見えず落ち着きやすい。",
        "力を抜いて10秒、落ち着いていられたら「Yes」→おやつ。引っ込めたら持つ時間を短くしてやり直す。",
      ],
      criterion: "足を持っても引っ込めず、力を抜いて10秒。これが5回できれば合格。",
      reason: "“我慢して耐える”のではなく、“リラックスして任せる”土台を作る。",
      testType: "duration",
      measure: { holdSeconds: 10, reps: 5 },
      requires: ["paws:L2"],
    },
    {
      level: 3,
      condition: "道具の感触と音に慣らす。",
      steps: [
        "爪切りを爪に当てる、または空打ちの音を鳴らす（まだ切らない）。",
        "嫌がらなければ「Yes」→おやつ。",
      ],
      criterion: "嫌がらず受け入れる、10回中8回。",
      reason: "道具の感触と音に慣れる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["nails:L2"],
    },
    {
      level: 4,
      condition: "1本だけ切る。",
      steps: [
        "止血剤（なければ片栗粉）を手元に用意してから始める。",
        "白い爪はピンクの血管の2mm手前を切る。黒い爪は先端から薄く削り、切り口に黒い／灰色の点が見えたら止める。",
        "リックマットをなめさせながら、1本だけ切る→「Yes」→おやつ。1日1本でもよい。",
        "万一出血したら、止血剤を切り口に数十秒押し当てる。その日は終了し、おやつで終わる。",
      ],
      criterion: "暴れず1本切れる、10回中8回。",
      reason: "「切る」を成功体験にする。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["nails:L3"],
    },
    {
      level: 5,
      condition: "片足分を切る。",
      steps: [
        "片足分（4〜5本）を続けて切る。",
        "各足、落ち着いて最後まで切れればOK。",
      ],
      criterion: "各足、落ち着いて最後まで切れる。",
      reason: "まとめて切れるようにする。",
      testType: "trial",
      measure: { reps: 4 },
      requires: ["nails:L4"],
    },
    {
      level: 6,
      condition: "全部の足を、力を抜いたまま切らせる。",
      steps: [
        "全部の足を、力を抜いた姿勢のまま最後まで切る。",
        "暴れず・固まらず完了できればOK。",
      ],
      criterion: "暴れず・固まらず、最後まで完了できれば合格（1回）。",
      reason: "自宅で爪切りが完結する（リラックスして任せられる）。",
      testType: "trial",
      measure: { successes: 1 },
      requires: ["nails:L5"],
    },
  ],

  bath: [
    {
      level: 1,
      condition: "お風呂場に慣らす。",
      steps: [
        "乾いた状態で、お風呂場に入っておやつ。",
        "怖がらず入室できればOK。",
      ],
      criterion: "怖がらず入室する、5回。",
      reason: "浴室を「怖くない場所」にする。",
      testType: "trial",
      measure: { successes: 5 },
      requires: ["body-handling:L1"],
    },
    {
      level: 2,
      condition: "お風呂場で過ごさせる。",
      steps: [
        "乾いた状態で、お風呂場に滞在する。",
        "落ち着いて1分過ごせればOK。",
      ],
      criterion: "落ち着いて1分間過ごせる、3回。",
      reason: "浴室に居続けられる。",
      testType: "duration",
      measure: { holdSeconds: 60, reps: 3 },
      requires: ["bath:L1"],
    },
    {
      level: 3,
      condition: "シャワーの音に慣らす。",
      steps: [
        "シャワーの音を、弱く・離れた位置から鳴らす。リックマットをなめさせながらだと落ち着きやすい。",
        "逃げなければ「Yes」→おやつ。少しずつ音量を上げ・距離を近づける。",
      ],
      criterion: "逃げない、10回中8回。",
      reason: "水の音に慣れる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["bath:L2"],
    },
    {
      level: 4,
      condition: "足先を水に慣らす。",
      steps: [
        "足先を、ぬるま湯（人肌・約36〜38℃）でそっと濡らす。",
        "引っ込めず受け入れたら「Yes」→おやつ。",
      ],
      criterion: "引っ込めず受け入れる、10回中8回。",
      reason: "水に少しずつ慣らす。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["bath:L3", "paws:L1"],
    },
    {
      level: 5,
      condition: "体に湯をかける。",
      steps: [
        "体に、ぬるま湯をやさしくかける（耳に水が入らないように）。",
        "暴れず受け入れたら「Yes」→おやつ。",
      ],
      criterion: "暴れず受け入れる、10回中8回。",
      reason: "全身に水をかけられる。",
      testType: "trial",
      measure: { trials: 10, successes: 8 },
      requires: ["bath:L4"],
    },
    {
      level: 6,
      condition: "全身を洗う。",
      steps: [
        "滑り止めマットの上に立たせ、犬用シャンプーを薄めて体→脚の順に洗う。顔は最後にスポンジで。",
        "すすぎ残しがないようよく流し、タオルでしっかり拭く。最後まで落ち着いて完了できればOK。",
      ],
      criterion: "最後まで落ち着いて入浴を完了する、1回。",
      reason: "自宅でお風呂に入れられる。",
      testType: "trial",
      measure: { successes: 1 },
      requires: ["bath:L5"],
    },
  ],
};

// コマンド＋ケアを統合したレベル辞書（アプリ・Webから一括参照する）
export const allLevels: Record<string, CommandLevel[]> = {
  ...commandLevels,
  ...careLevels,
};
